Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2018-08, with the labels that each got.

#718 Update third-party-software-updates.md
  sccm/sum/deploy-use/third-party-software-updates.md
Labels: Change sent to author, ready-to-merge

#719 From private repo
  sccm/core/servers/deploy/configure/about-the-service-connection-point.md
  sccm/core/servers/manage/recover-sites.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: Change sent to author, do-not-merge

#722 From private repo
  sccm/core/clients/manage/co-management-overview.md
Labels: Change sent to author, do-not-merge

#721 Update Incremental update intervals
  sccm/core/clients/manage/collections/create-collections.md
Labels: Change sent to author, ready-to-merge, triaged

#723 Update incremental update intervals
  sccm/core/clients/manage/collections/create-collections.md
Labels: Change sent to author, ready-to-merge

#730 Rename Sharepoint to Skype
  sccm/mdm/deploy-use/manage-access-to-services.md
Labels: Change sent to author, ready-to-merge

#734 Update setup-downloader.md
  sccm/core/servers/deploy/install/setup-downloader.md
Labels: Change sent to author, ready-to-merge

#737 Update certificates-for-cloud-management-gateway.md
  sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md
Labels: Change sent to author, do-not-merge

#743 Added Log file Tip to cmpivot.md
  sccm/core/servers/manage/cmpivot.md
Labels: Change sent to author, ready-to-merge

#746 From private repo
  sccm/core/clients/manage/plan-internet-based-client-management.md
Labels: do-not-merge

#745 Add new reports to the list
  sccm/core/servers/manage/list-of-reports.md
Labels: Change sent to author, ready-to-merge

#704 Update fundamentals-of-security.md
  sccm/core/understand/fundamentals-of-security.md
Labels: Change sent to author, needs-more-info, ready-to-merge, triaged

#748 Fixed Tables with Single Blank Headers
  sccm/develop/reference/compliance/sms_dcmdeploymentcompliantdetailsperasset-server-wmi-class.md
  sccm/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class.md
  sccm/develop/reference/core/clients/deploy/sms_clientdeploymentcollectionbucket-server-wmi-class.md
  sccm/develop/reference/core/clients/sdk/ccm_appdeploymenttype-client-wmi-class.md
  sccm/develop/reference/core/clients/sdk/ccm_application-client-wmi-class.md
  sccm/develop/reference/core/clients/sdk/ccm_applicationpolicy-client-wmi-class.md
  sccm/develop/reference/core/clients/sdk/ccm_cievaluationjob-client-wmi-class.md
  sccm/develop/reference/core/clients/sdk/downloadcontents-method-in-class-ccm_application.md
  sccm/develop/reference/core/clients/sdk/evaluateapppolicy-method-in-class-ccm_applicationpolicy.md
  sccm/develop/reference/core/clients/sdk/install-method-in-class-ccm_application.md
  sccm/develop/reference/core/clients/sdk/uninstall-method-in-class-ccm_application.md
  sccm/develop/reference/core/servers/configure/sms_azureservice-server-wmi-class.md
  sccm/develop/reference/core/servers/configure/sms_sci_sqltask-server-wmi-class.md
  sccm/develop/reference/misc/sms_sci_roamingboundary-server-wmi-class.md
  sccm/develop/reference/osd/sms_tasksequence_downloadpackagecontentaction-server-wmi-class.md
  sccm/develop/reference/osd/sms_tasksequence_pointer-server-wmi-class.md
  sccm/develop/reference/osd/sms_winpeoptionalcomponentinfo-server-wmi-class.md
Labels: Change sent to author, ready-to-merge

#758 From private repo
  .openpublishing.redirection.json
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/plan-design/configs/support-for-sql-server-versions.md
  sccm/core/servers/deploy/configure/high-availability-options.md
  sccm/index.md
  sccm/mdm/TOC.md
  sccm/mdm/deploy-use/change-mdm-authority.md
  sccm/mdm/deploy-use/lookout-mobile-threat-defense-in-configuration-manager.md
  sccm/mdm/deploy-use/migrate-hybridmdm-to-intunesa.md
  sccm/mdm/deploy-use/migrate-mixed-authority.md
  sccm/mdm/deploy-use/mobile-threat-defense.md
  sccm/mdm/deploy-use/setup-hybrid-mdm.md
  sccm/mdm/deploy-use/wipe-lock-reset-devices.md
  sccm/mdm/plan-design/plan-hybrid-mobile-device-management.md
  sccm/mdm/plan-design/supported-device-platforms-for-hybrid.md
  sccm/mdm/understand/choose-between-standalone-intune-and-hybrid-mobile-device-management.md
  sccm/mdm/understand/hybrid-mobile-device-management.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
  sccm/protect/deploy-use/configuration-manager-mobile-threat-defense.md
  sccm/sum/deploy-use/third-party-software-updates.md
Labels: Change sent to author, do-not-merge

#736 Update removal of EnableSQM parameter
  sccm/core/servers/deploy/install/install-consoles.md
Labels: Change sent to author, ready-to-merge

#760 Update create-a-task-sequence-to-capture-and-restore-user-state.md
  sccm/osd/deploy-use/create-a-task-sequence-to-capture-and-restore-user-state.md
Labels: Change sent to author, ready-to-merge

#762 From private repo
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: Change sent to author, do-not-merge

#767 From private repo
  sccm/sum/deploy-use/third-party-software-updates.md
Labels: Change sent to author, do-not-merge

#707 Update configure-role-based-administration.md
  sccm/core/servers/deploy/configure/configure-role-based-administration.md
Labels: Change sent to author, do-not-merge, doc-bug, triaged

#778 From private repo
  sccm/core/get-started/capabilities-in-technical-preview-1805.md
  sccm/core/plan-design/configs/site-and-site-system-prerequisites.md
  sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md
  sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md
  sccm/core/servers/deploy/install/release-notes.md
  sccm/core/servers/manage/cmpivot.md
  sccm/mdm/deploy-use/actions-for-noncompliance.md
  sccm/mdm/deploy-use/migrate-mixed-authority.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
  sccm/osd/TOC.md
  sccm/osd/deploy-use/custom-task-sequence-scenarios.md
  sccm/sum/deploy-use/automatically-deploy-software-updates.md
Labels: do-not-merge

#768 ADK version support for Server OS deployment
  sccm/core/plan-design/configs/support-for-windows-10.md
Labels: Change sent to author, ready-to-merge

#781 From private repo
  .openpublishing.redirection.json
  sccm/core/TOC.md
  sccm/core/clients/manage/collections/manage-collections.md
  sccm/core/get-started/capabilities-in-technical-preview-1808.md
  sccm/core/get-started/includes/1357866.md
  sccm/core/get-started/includes/1358146.md
  sccm/core/get-started/includes/1358926.md
  sccm/core/get-started/includes/feature-include-template.md
  sccm/core/get-started/includes/known-issue-include-template.md
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/plan-design/hierarchy/client-peer-cache.md
  sccm/core/servers/manage/checklist-for-installing-update-1806.md
  sccm/core/servers/manage/install-in-console-updates.md
  sccm/docfx.json
  sccm/osd/TOC.md
  sccm/osd/deploy-use/create-a-task-sequence-to-capture-and-restore-user-state.md
  sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md
  sccm/osd/deploy-use/manage-task-sequences-to-automate-tasks.md
  sccm/osd/get-started/associate-users-with-a-destination-computer.md
  sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic.md
  sccm/osd/plan-design/planning-considerations-for-automating-tasks.md
  sccm/osd/understand/task-sequence-action-variables.md
  sccm/osd/understand/task-sequence-built-in-variables.md
  sccm/osd/understand/task-sequence-steps.md
  sccm/osd/understand/task-sequence-variables.md
  sccm/osd/understand/using-task-sequence-variables.md
Labels: Change sent to author, do-not-merge

#787 URL fix for using task sequence variables
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
Labels: Change sent to author, ready-to-merge

#792 From private repo
  sccm/core/servers/manage/backup-and-recovery.md
Labels: Change sent to author

#796 Updating MDM support to "Windows Holographic for Business"
  sccm/mdm/includes/mdm-supported-devices.md
Labels: Change sent to author, do-not-merge

#801 From private repo
  sccm/apps/TOC.md
  sccm/apps/TOC.yml
  sccm/compliance/TOC.md
  sccm/compliance/TOC.yml
  sccm/core/TOC.md
  sccm/core/TOC.yml
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/develop/TOC.md
  sccm/develop/TOC.yml
  sccm/develop/reference/TOC.md
  sccm/develop/reference/TOC.yml
  sccm/mdm/TOC.md
  sccm/mdm/TOC.yml
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
  sccm/mdt/TOC.md
  sccm/mdt/TOC.yml
  sccm/osd/TOC.md
  sccm/osd/TOC.yml
  sccm/protect/TOC.md
  sccm/protect/TOC.yml
  sccm/sum/TOC.md
  sccm/sum/TOC.yml
Labels: Change sent to author, do-not-merge

#804 From private repo
  sccm/apps/TOC.yml
  sccm/apps/pcm/error-messages.md
  sccm/apps/pcm/how-to-analyze-and-convert.md
  sccm/apps/pcm/how-to-use-plug-in.md
  sccm/apps/pcm/media/1357861-pcm-dashboard.png
  sccm/apps/pcm/package-conversion-manager.md
  sccm/apps/pcm/plugin-config-xml.md
  sccm/apps/pcm/troubleshoot-pcm.md
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/servers/manage/pre-release-features.md
Labels: do-not-merge

#805 From private repo
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/servers/deploy/configure/configure-discovery-methods.md
  sccm/mdm/deploy-use/create-vpn-profiles.md
Labels: Change sent to author, do-not-merge
