Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2018-10, with the labels that each got.

#874 Update use-a-task-sequence-to-manage-virtual-hard-disks.md
  sccm/osd/deploy-use/use-a-task-sequence-to-manage-virtual-hard-disks.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#889 fix typo
  sccm/osd/deploy-use/create-a-task-sequence-to-capture-an-operating-system.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#894 Remove extra characters
  sccm/core/plan-design/security/cryptographic-controls-technical-reference.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#880 Added link to sms_advertisement class
  sccm/develop/core/servers/configure/how-to-create-an-advertisement.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#903 Update assign-clients-to-a-site.md
  sccm/core/clients/deploy/assign-clients-to-a-site.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#884 Update Alert for outdated malware client
  sccm/protect/deploy-use/endpoint-configure-alerts.md
Labels: ready-to-merge

#891 Fixed last bullet that ended mid-sentence.
  sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#899 Update sms_tasksequence_applywindowssettingsaction-server-wmi-class.md to fix small mistake with Local administrator password info
  sccm/develop/reference/osd/sms_tasksequence_applywindowssettingsaction-server-wmi-class.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#900 Added command-line options for completeness
  sccm/core/servers/manage/admin-console.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#906 From private repo
  sccm/core/get-started/capabilities-in-technical-preview-1810.md
  sccm/core/get-started/includes/1810/1358270.md
  sccm/core/get-started/technical-preview.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#907 Update endpoint-definitions-network.md
  sccm/protect/deploy-use/endpoint-definitions-network.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#909 Changed the priority list
  sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#897 Corrects a typo: sever -> server
  .openpublishing.redirection.json
  sccm/core/servers/manage/use-the-service-connection-tool.md
  sccm/develop/reference/TOC.yml
  sccm/develop/reference/core/clients/deploy/client-deployment-server-wmi-classes.md
  sccm/develop/reference/core/clients/deploy/sms_clientbaseline-server-wmi-class.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#915 From private repo
  sccm/core/misc/in-console-documentation.md
  sccm/develop/core/servers/configure/how-to-create-an-advertisement.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#916 Add how clients determine if they are ICBM or not
  sccm/core/clients/manage/plan-internet-based-client-management.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#931 wrong tense
  sccm/compliance/understand/ensure-device-compliance.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#932 Minor grammar changes
  sccm/compliance/understand/ensure-device-compliance.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#935 Fix typo in create-updates-with-updates-publisher.md
  sccm/sum/tools/create-updates-with-updates-publisher.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#942 From private repo
  sccm/core/get-started/capabilities-in-technical-preview-1810.md
  sccm/core/get-started/includes/1810/1358333.md
  sccm/mdm/understand/hybrid-mobile-device-management.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#876 Add cmdlet reference for ADR Deployment creation
  sccm/sum/deploy-use/automatically-deploy-software-updates.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#930 Misspelling
  sccm/core/servers/manage/modify-your-infrastructure.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#943 Add bullet item about removing web apps before migration
  sccm/mdm/deploy-use/migrate-import-data.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#948 From private repo
  sccm/core/TOC.yml
  sccm/core/get-started/capabilities-in-technical-preview-1810-2.md
  sccm/core/get-started/includes/1810-2/1317364.md
  sccm/core/get-started/includes/1810-2/1357013.md
  sccm/core/get-started/includes/1810-2/1358008.md
  sccm/core/get-started/includes/1810-2/1358981.md
  sccm/core/get-started/includes/1810-2/1359029.md
  sccm/core/get-started/includes/1810-2/1359181.md
  sccm/core/get-started/technical-preview.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#944 No need to check "Windows Technical Preview 2"
  sccm/protect/deploy-use/endpoint-definitions-wsus.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#945 Insert "site" between "The" and "assigns" (missing noun)
  sccm/core/plan-design/hierarchy/plan-for-site-system-servers-and-site-system-roles.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#947 Update Visio Sample Query
  sccm/core/servers/manage/create-queries.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#949 From private repo
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#951 Extra, unneccesary word 'but'
  sccm/core/plan-design/security/cryptographic-controls-technical-reference.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#956 typo: Double word "this"
  sccm/develop/reference/core/servers/configure/sms_dpstatusinfo-server-wmi-class.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#961 chore: Remove manual @ for PR template
  PULL_REQUEST_TEMPLATE.md
Labels: Change sent to author, do-not-merge

#952 chore: Remove empty vscode settings
  .vscode/settings.json
Labels: Change sent to author, do-not-merge

#957 typo: Double word "the"
  sccm/develop/core/understand/windows-powershell-basics.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#958 typo: Double word "something"
  sccm/develop/core/understand/introduction-to-wbemtest.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#953 typo: Double word "in"
  sccm/mdt/toolkit-reference.md
  sccm/mdt/use-the-mdt.md
Labels: do-not-merge

#954 typo: Double word "type"
  sccm/mdt/use-the-mdt.md
Labels: do-not-merge

#955 typo: Double word "is"
  sccm/mdt/use-the-mdt.md
Labels: do-not-merge

#962 Update manage-operating-system-images.md
  sccm/osd/get-started/manage-operating-system-images.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#963 Update manage-operating-system-upgrade-packages.md
  sccm/osd/get-started/manage-operating-system-upgrade-packages.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#965 Update use-pxe-to-deploy-windows-over-the-network.md
  sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#969 Updated Note
  sccm/core/clients/deploy/plan/considerations-for-managing-clients-in-a-vdi.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#970 Revise CMPivot permissions prereq
  sccm/core/servers/manage/cmpivot.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#975 From private repo
  sccm/core/get-started/includes/1810-2/1358008.md
  sccm/protect/deploy-use/endpoint-configure-alerts.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#978 Fix broken "Accessibility Features" link.
  sccm/core/servers/manage/admin-console.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#982 Update co-management-prepare.md
  sccm/core/clients/manage/co-management-prepare.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#990 From private repo
  .openpublishing.redirection.json
  sccm/core/TOC.yml
  sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md
  sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md
  sccm/core/clients/manage/inventory/configure-hardware-inventory.md
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/plan-design/hierarchy/accounts.md
  sccm/core/plan-design/hierarchy/client-peer-cache.md
  sccm/core/plan-design/hierarchy/communications-between-endpoints.md
  sccm/core/plan-design/hierarchy/enhanced-http.md
  sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md
  sccm/core/plan-design/hierarchy/manage-accounts-to-access-content.md
  sccm/core/plan-design/hierarchy/security-and-privacy-for-content-management.md
  sccm/core/plan-design/security/configure-security.md
  sccm/core/plan-design/security/plan-for-security.md
  sccm/core/servers/deploy/configure/site-components.md
  sccm/core/servers/manage/pre-release-features.md
  sccm/core/understand/fundamentals-of-security.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
  sccm/osd/deploy-use/deploy-windows-to-go.md
  sccm/osd/plan-design/planning-considerations-for-automating-tasks.md
  sccm/osd/plan-design/security-and-privacy-for-operating-system-deployment.md
Labels: do-not-merge
