Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2018-07, with the labels that each got.

#651 From private repo
  sccm/core/servers/deploy/install/language-packs.md
Labels: Change sent to author, do-not-merge

#654 From private repo
  sccm/core/servers/deploy/configure/about-the-service-connection-point.md
Labels: Change sent to author, do-not-merge

#657 From private repo
  sccm/mdm/deploy-use/manage-internet-access-using-managed-browser-policies.md
Labels: do-not-merge

#661 From private repo
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: Change sent to author, do-not-merge

#664 From private repo
  sccm/mdm/deploy-use/enable-lookout-connection-in-intune.md
Labels: Change sent to author, do-not-merge

#676 From private repo
  sccm/mdm/deploy-use/device-compliance-policies.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: do-not-merge

#672 Update packages-and-programs.md
  sccm/apps/deploy-use/packages-and-programs.md
Labels: Change sent to author, ready-to-merge

#673 Update manage-task-sequences-to-automate-tasks.md
  sccm/osd/deploy-use/manage-task-sequences-to-automate-tasks.md
Labels: Change sent to author, ready-to-merge

#682 Update note for supersedence auto upgrade
  sccm/apps/deploy-use/deploy-applications.md
Labels: Change sent to author, ready-to-merge

#689 Updated Application auto-upgrade supersedence
  sccm/core/plan-design/changes/whats-new-in-version-1802.md
Labels: Change sent to author, ready-to-merge

#691 Update endpoint-configure-alerts.md
  sccm/protect/deploy-use/endpoint-configure-alerts.md
Labels: Change sent to author, ready-to-merge

#695 Update content-library-cleanup-tool.md
  sccm/core/plan-design/hierarchy/content-library-cleanup-tool.md
Labels: Change sent to author, ready-to-merge

#697 Removed AMT and OOB references
  sccm/core/plan-design/network/pki-certificate-requirements.md
Labels: Change sent to author, ready-to-merge

#700 chore: Remove Git file copied to root
  FETCH_HEAD
Labels: Change sent to author, ready-to-merge

#703 Edit URLs for HTTPS and remove duplicates
  sccm/core/understand/learn-more-editions.md
Labels: Change sent to author, ready-to-merge

#705 Updated randomization scan setting
  sccm/protect/deploy-use/endpoint-antimalware-policies.md
Labels: Change sent to author, ready-to-merge

#712 Typo - Configuration incorrectly spelt
  sccm/core/servers/deploy/configure/boundaries.md
Labels: Change sent to author, ready-to-merge
