Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2018-09, with the labels that each got.

#827 Update third-party-software-updates.md
  sccm/sum/deploy-use/third-party-software-updates.md
Labels: ready-to-merge

#849 From private repo
  sccm/index.md
Labels: Change sent to author, do-not-merge

#833 Update site-and-site-system-prerequisites.md
  sccm/core/plan-design/configs/site-and-site-system-prerequisites.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#842 Update co-management-dashboard.md
  sccm/core/clients/manage/co-management-dashboard.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#844 Update use-a-task-sequence-to-manage-virtual-hard-disks.md
  sccm/osd/deploy-use/use-a-task-sequence-to-manage-virtual-hard-disks.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#852 Update health-attestation.md
  sccm/core/servers/manage/health-attestation.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#853 From private repo
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#857 From private repo
  sccm/core/misc/cm07-eos.md
Labels: do-not-merge

#858 Script examples were broken - can't use non-existing folder
  sccm/sum/deploy-use/service-a-server-group.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#859 From private repo
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/plan-design/hierarchy/client-peer-cache.md
  sccm/core/plan-design/hierarchy/the-content-library.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#862 Update certificates-for-cloud-management-gateway.md
  sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#864 From private repo
  sccm/core/get-started/capabilities-in-technical-preview-1805.md
  sccm/core/get-started/includes/1359068.md
  sccm/core/plan-design/changes/whats-new-in-version-1610.md
  sccm/core/plan-design/changes/whats-new-in-version-1702.md
  sccm/core/plan-design/changes/whats-new-in-version-1706.md
  sccm/core/plan-design/changes/whats-new-in-version-1710.md
  sccm/core/servers/manage/cmpivot.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge
