Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2018-06, with the labels that each got.

#573 From private repo
  sccm/sum/deploy-use/integrate-windows-update-for-business-windows-10.md
Labels: Change sent to author, do-not-merge

#576 From private repo
  sccm/mdm/deploy-use/configure-and-deploy-lookout-for-work-apps.md
  sccm/mdm/deploy-use/enable-lookout-connection-in-intune.md
  sccm/mdm/deploy-use/enroll-hybrid-android.md
  sccm/mdm/deploy-use/media/aad-add-app-reg.png
  sccm/mdm/deploy-use/media/aad-add-app.png
  sccm/mdm/deploy-use/media/aad_group_object_id.png
  sccm/mdm/deploy-use/media/aad_tenant_name.png
  sccm/mdm/deploy-use/media/lookout-intune-synchronization.png
  sccm/mdm/deploy-use/set-up-your-subscription-with-lookout.md
  sccm/mdm/understand/whats-new-hybrid-archive.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: do-not-merge

#577 Update software-center.md
  sccm/core/understand/software-center.md
Labels: Change sent to author, ready-to-merge

#585 From private repo
  .openpublishing.redirection.json
  sccm/core/TOC.md
  sccm/core/get-started/capabilities-in-technical-preview-1806.md
  sccm/core/get-started/media/1357861-pcm-dashboard.png
  sccm/core/get-started/technical-preview.md
  sccm/core/misc/eula/third-party-notices.md
  sccm/mdm/deploy-use/enroll-hybrid-android.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
  sccm/mdt/TOC.md
  sccm/mdt/index.yml
  sccm/mdt/release-notes.md
  sccm/mdt/whats-new-in-mdt.md
Labels: Change sent to author, do-not-merge

#586 Updated metadata and lang neutral URLs as possible
  sccm/core/understand/learn-more-editions.md
Labels: Change sent to author, ready-to-merge

#590 From private repo
  sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md
Labels: Change sent to author, do-not-merge

#591 From private repo
  sccm/core/servers/manage/checklist-for-installing-update-1802.md
Labels: Change sent to author, do-not-merge

#597 From private repo
  sccm/core/get-started/capabilities-in-technical-preview-1806.md
  sccm/core/plan-design/changes/whats-new-in-version-1802.md
  sccm/core/servers/manage/pre-release-features.md
  sccm/mdm/deploy-use/create-vpn-profiles.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: Change sent to author, do-not-merge

#598 Update publish-site-data.md
  sccm/core/servers/deploy/configure/publish-site-data.md
Labels: Change sent to author, ready-to-merge

#599 Update data-warehouse.md
  sccm/core/servers/manage/data-warehouse.md
Labels: Change sent to author, ready-to-merge

#600 Update ports.md
  sccm/core/plan-design/hierarchy/ports.md
Labels: Change sent to author, ready-to-merge

#604 Update triggerschedule-method-in-class-sms_client.md
  sccm/develop/reference/core/clients/client-classes/triggerschedule-method-in-class-sms_client.md
Labels: Change sent to author, ready-to-merge

#606 Update database-replicas-for-management-points.md
  sccm/core/servers/deploy/configure/database-replicas-for-management-points.md
Labels: Change sent to author, ready-to-merge

#610 Fixed typo and added a space
  sccm/core/plan-design/network/pki-certificate-requirements.md
Labels: Change sent to author, ready-to-merge

#615 Additional description on running Computer Enrollment wizard automati…
  sccm/core/clients/manage/upgrade/upgrade-clients-on-mac-computers.md
Labels: Change sent to author, ready-to-merge

#614 Change "Windows Reccomends" to "Microsoft Reccomends" under Widnos AD…
  sccm/core/plan-design/configs/support-for-windows-10.md
Labels: Change sent to author, ready-to-merge

#613 Update list-of-reports.md
  sccm/core/servers/manage/list-of-reports.md
Labels: Change sent to author, ready-to-merge

#629 Amended copy
  sccm/sum/deploy-use/manage-office-365-proplus-updates.md
Labels: Change sent to author, ready-to-merge

#623 From private repo
  sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md
  sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md
  sccm/core/understand/configuration-manager-and-windows-as-service.md
  sccm/sum/TOC.md
  sccm/sum/deploy-use/manage-express-installation-files-for-windows-10-updates.md
  sccm/sum/deploy-use/optimize-windows-10-update-delivery.md
Labels: Change sent to author, do-not-merge

#634 Link to Configure hardware inventory
  sccm/sum/deploy-use/manage-office-365-proplus-updates.md
Labels: Change sent to author, ready-to-merge

#635 Wording issue.
  sccm/core/clients/manage/inventory/configure-hardware-inventory.md
Labels: Change sent to author, ready-to-merge

#636 Fixed typo in metadata subtitle (Configuraton > Configuration)
  sccm/core/clients/manage/upgrade/upgrade-analytics.md
Labels: Change sent to author, ready-to-merge

#638 Update to better refelct post 1710 Support lifecycle
  sccm/core/plan-design/changes/whats-new-incremental-versions.md
Labels: Change sent to author, ready-to-merge

#637 Update text to reflect post 1710 Support lifecycle
  sccm/core/understand/which-branch-should-i-use.md
Labels: Change sent to author, ready-to-merge

#647 From private repo
  sccm/core/TOC.md
  sccm/core/get-started/capabilities-in-technical-preview-1806-2.md
  sccm/core/get-started/media/1358577-phased-deployment-status.png
  sccm/core/get-started/technical-preview.md
  sccm/mdm/deploy-use/create-vpn-profiles.md
Labels: Change sent to author, do-not-merge
