Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2019-09, with the labels that each got.

#1846 From private repo
  sccm/apps/TOC.yml
  sccm/apps/deploy-use/create-deploy-scripts.md
  sccm/apps/deploy-use/manage-apps-from-the-windows-store-for-business.md
  sccm/apps/deploy-use/troubleshoot-microsoft-store-for-business-integration.md
  sccm/comanage/how-to-switch-workloads.md
  sccm/compliance/deploy-use/upgrade-windows-version.md
  sccm/core/TOC.yml
  sccm/core/get-started/2019/includes/1908-2/3197353.md
  sccm/core/get-started/2019/includes/1908-2/3785535.md
  sccm/core/get-started/2019/includes/1908-2/4923997.md
  sccm/core/get-started/2019/includes/1908-2/5138936.md
  sccm/core/get-started/2019/media/4923997-message-administrator.png
  sccm/core/get-started/2019/technical-preview-1908-2.md
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/hierarchy/log-files.md
  sccm/core/plan-design/network/internet-endpoints.md
  sccm/core/servers/manage/cmpivot.md
  sccm/desktop-analytics/faq.md
  sccm/desktop-analytics/set-up.md
  sccm/desktop-analytics/whats-new.md
  sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md
  sccm/sum/deploy-use/integrate-windows-update-for-business-windows-10.md
  sccm/sum/plan-design/plan-for-software-updates.md
Labels: do-not-merge

#1854 From private repo
  sccm/apps/TOC.yml
  sccm/comanage/quickstart-conditional-access.md
  sccm/comanage/toc.yml
  sccm/compliance/TOC.yml
  sccm/core/TOC.yml
  sccm/core/clients/manage/client-notification.md
  sccm/core/clients/manage/manage-clients.md
  sccm/core/plan-design/configs/support-for-windows-10.md
  sccm/core/servers/deploy/install/release-notes.md
  sccm/core/servers/manage/checklist-for-installing-update-1610.md
  sccm/core/servers/manage/checklist-for-installing-update-1702.md
  sccm/core/servers/manage/checklist-for-installing-update-1706.md
  sccm/core/servers/manage/checklist-for-installing-update-1710.md
  sccm/core/understand/product-and-licensing-faq.md
  sccm/desktop-analytics/faq.md
  sccm/desktop-analytics/overview.md
  sccm/desktop-analytics/tutorial-windows10.md
  sccm/develop/TOC.yml
  sccm/develop/osd/about-operating-system-deployment-image-management.md
  sccm/develop/reference/core/servers/configure/sms_distributionpoint-server-wmi-class.md
  sccm/develop/reference/core/servers/configure/sms_distributionpointinfo-server-wmi-class.md
  sccm/index.yml
  sccm/mdm/TOC.yml
  sccm/osd/TOC.yml
  sccm/protect/TOC.yml
  sccm/protect/deploy-use/create-deploy-exploit-guard-policy.md
  sccm/sum/TOC.yml
Labels: do-not-merge

#1857 From private repo
  sccm/desktop-analytics/faq.md
  sccm/desktop-analytics/overview.md
  sccm/osd/understand/task-sequence-steps.md
Labels: Change sent to author, configmgr-osd/tech, configuration-manager/prod, do-not-merge

#1862 From private repo
  .openpublishing.redirection.json
  sccm/comanage/how-to-switch-workloads.md
  sccm/comanage/workloads.md
  sccm/core/TOC.yml
  sccm/core/clients/manage/sync-data-log-analytics.md
  sccm/core/misc/in-console-documentation.md
Labels: do-not-merge

#1858 Peer Content Source State Messages
  sccm/core/plan-design/hierarchy/client-peer-cache.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#1880 From private repo
  sccm/core/servers/deploy/configure/boundary-groups.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#1872 Update triggerschedule-method-in-class-sms_client.md to table layout
  sccm/develop/reference/core/clients/client-classes/triggerschedule-method-in-class-sms_client.md
Labels: Change sent to author, assessing_(C&L), configmgr-sdk/tech, configuration-manager/prod, ready-to-merge

#1870 Changed what type of TSes are supported via CMG
  sccm/osd/deploy-use/deploy-a-task-sequence.md
Labels: Change sent to author, assessing_(C&L), configmgr-osd/tech, configuration-manager/prod, ready-to-merge

#1881 From private repo
  .openpublishing.publish.config.json
  sccm/core/servers/deploy/install/prepare-to-install-sites.md
Labels: do-not-merge

#1884 From private repo
  .openpublishing.publish.config.json
Labels: do-not-merge, review-team-triage

#1887 From private repo
  sccm/osd/deploy-use/configure-precache-content.md
Labels: Change sent to author, configmgr-osd/tech, configuration-manager/prod, do-not-merge

#1889 typo in cmpivot.md
  sccm/core/servers/manage/cmpivot.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#1890 From private repo
  sccm/core/servers/manage/cmpivot-tsg.md
  sccm/core/servers/manage/media/cmpivot-client-operationid-1902.png
  sccm/core/servers/manage/media/cmpivot-sql-queries-1902.png
Labels: do-not-merge

#1892 Updated Start CMPivot Permissions for new "Run CMPivot" permission available in 1906 and higher
  sccm/core/clients/manage/client-notification.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#1772 Update best-practices-for-collections.md
  sccm/core/clients/manage/collections/best-practices-for-collections.md
Labels: Change sent to author, assessing_(C&L), configmgr-client/tech, configuration-manager/prod, ready-to-merge

#1895 Update set-up-your-lab.md
  sccm/core/get-started/set-up-your-lab.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#1898 From private repo
  sccm/core/clients/manage/monitor-clients.md
  sccm/core/plan-design/configs/support-for-windows-10.md
  sccm/core/plan-design/network/extend-the-active-directory-schema.md
  sccm/core/support/deployment-monitoring-tool.md
  sccm/sum/get-started/configure-classifications-and-products.md
  sccm/sum/get-started/media/3556023-windows-insiders-pre-release-feature-update.png
Labels: do-not-merge

#1899 Removed the line
  sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, ready-to-merge

#1904 From private repo
  sccm/core/TOC.yml
  sccm/core/clients/manage/cmg/setup-cloud-management-gateway.md
  sccm/core/clients/manage/collections/best-practices-for-collections.md
  sccm/core/get-started/2019/includes/1909/3098816.md
  sccm/core/get-started/2019/includes/1909/3556022.md
  sccm/core/get-started/2019/includes/1909/3556023.md
  sccm/core/get-started/2019/includes/1909/3601034.md
  sccm/core/get-started/2019/includes/1909/3601238.md
  sccm/core/get-started/2019/includes/1909/5410930.md
  sccm/core/get-started/2019/includes/1909/5411057.md
  sccm/core/get-started/2019/media/3098816-select-resources.png
  sccm/core/get-started/2019/media/3556022-azure-information-tab.png
  sccm/core/get-started/2019/media/3556022-run-powershell-script-deployment.png
  sccm/core/get-started/2019/media/3556022-site-server-passive-mode.png
  sccm/core/get-started/2019/media/3556022-site-system-roles-tab.png
  sccm/core/get-started/2019/technical-preview-1905.md
  sccm/core/get-started/2019/technical-preview-1909.md
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/changes/whats-new-in-version-1902.md
  sccm/core/plan-design/changes/whats-new-in-version-1906.md
  sccm/core/plan-design/configs/site-size-performance-guidelines.md
  sccm/desktop-analytics/overview.md
  sccm/desktop-analytics/set-up.md
  sccm/mdm/understand/hybrid-mobile-device-management.md
  sccm/osd/deploy-use/create-bootable-media.md
  sccm/osd/deploy-use/create-capture-media.md
  sccm/osd/deploy-use/create-stand-alone-media.md
Labels: do-not-merge
