Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2019-02, with the labels that each got.

#1220 From private repo
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/core/plan-design/choose-a-device-management-solution.md
  sccm/sum/deploy-use/uup-preview.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1115 Update about Schedule re-evaluation for deployment
  sccm/core/clients/deploy/about-client-settings.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1224 Formatting Fixes
  sccm/develop/reference/core/servers/configure/sms_distributionpointinfo-server-wmi-class.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1227 Clarified wording on which SQL query engine to use
  sccm/core/servers/deploy/install/list-of-prerequisite-checks.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1228 Update install-and-configure-distribution-points.md
  sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1231 Update proxy-server-support.md
  sccm/core/plan-design/network/proxy-server-support.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1232 From private repo
  sccm/comanage/how-to-prepare-Win10.md
  sccm/core/TOC.yml
  sccm/core/get-started/2019/includes/1902/3231732.md
  sccm/core/get-started/2019/includes/1902/3555947.md
  sccm/core/get-started/2019/includes/1902/3556021.md
  sccm/core/get-started/2019/includes/1902/3599209.md
  sccm/core/get-started/2019/includes/1902/3612112.md
  sccm/core/get-started/2019/includes/1902/3640932.md
  sccm/core/get-started/2019/includes/1902/3705507.md
  sccm/core/get-started/2019/includes/1902/3747129.md
  sccm/core/get-started/2019/media/3555947-required-dialog.png
  sccm/core/get-started/2019/media/3555947-required-toast.png
  sccm/core/get-started/2019/media/3555947-restart-dialog.png
  sccm/core/get-started/2019/media/3555947-restart-toast.png
  sccm/core/get-started/2019/media/3747129-installation-progress.png
  sccm/core/get-started/2019/technical-preview-1902.md
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/desktop-analytics/set-up.md
  sccm/mdm/deploy-use/manage-access-to-o365-services-for-pcs-managed-by-sccm.md
  sccm/mdm/deploy-use/manage-access-to-services.md
  sccm/mdm/understand/hybrid-mobile-device-management.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1234 Update quickstart-hybrid-aad.md
  sccm/comanage/quickstart-hybrid-aad.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1233 Update manage-access-to-o365-services-for-pcs-managed-by-sccm.md
  sccm/mdm/deploy-use/manage-access-to-o365-services-for-pcs-managed-by-sccm.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1238 Update tutorial-office-365.md
  sccm/desktop-analytics/tutorial-office-365.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1239 Update enable-data-sharing.md
  sccm/desktop-analytics/enable-data-sharing.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1241 Update list-of-prerequisite-checks.md
  sccm/core/servers/deploy/install/list-of-prerequisite-checks.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1243 Update 'Common Failures' Statement
  sccm/core/servers/manage/checklist-for-installing-update-1810.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1244 From private repo
  template.md
Labels: do-not-merge

#1247 Update log-files.md
  sccm/core/plan-design/hierarchy/log-files.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1245 Update Windows 10 servicing URL
  sccm/core/servers/deploy/configure/about-the-service-connection-point.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1252 From private repo
  sccm/apps/deploy-use/create-deploy-scripts.md
  sccm/mdm/deploy-use/migrate-mixed-authority.md
  sccm/sum/get-started/configure-classifications-and-products.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1258 From private repo
  sccm/core/TOC.yml
  sccm/core/get-started/2019/includes/1902-2/3555946.md
  sccm/core/get-started/2019/includes/1902-2/3555955.md
  sccm/core/get-started/2019/includes/1902-2/3735402.md
  sccm/core/get-started/2019/includes/1902-2/3798957.md
  sccm/core/get-started/2019/technical-preview-1902-2.md
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
  sccm/sum/deploy-use/software-updates-maintenance.md
  sccm/sum/deploy-use/uup-preview.md
  sccm/sum/tools/install-updates-publisher.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1257 Duplicate table
  sccm/protect/deploy-use/endpoint-protection-client-faq.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1261 From private repo
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/core/plan-design/configs/size-and-scale-numbers.md
  sccm/core/servers/manage/admin-console.md
  sccm/core/understand/software-center.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1263 Update endpoint-definitions-configmgr.md
  sccm/protect/deploy-use/endpoint-definitions-configmgr.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1262 Update endpoint-definitions-configmgr.md
  sccm/protect/deploy-use/endpoint-definitions-configmgr.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1264 From private repo
  sccm/core/servers/deploy/install/release-notes.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1265 Removing the point of adding a new UI for setting tab visibility
  sccm/core/get-started/2019/includes/1902/3612112.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1272 Updated DPMP
  sccm/core/get-started/azure-template.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1271 More specific about CMG supported task sequences
  sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1273 From private repo
  sccm/apps/get-started/creating-windows-applications.md
  sccm/comanage/quickstart-autopilot.md
  sccm/core/TOC.yml
  sccm/core/misc/eula/microsoft-sql-server-2014-shared-management-objects.md
  sccm/core/misc/eula/microsoft-sql-server-2016-express.md
  sccm/core/misc/eula/microsoft-sql-server-compact-4.0-service-pack-1-sp1.md
  sccm/core/misc/eula/microsoft-system-center-configuration-manager-supplemental-placeholder-eula.md
  sccm/core/misc/eula/microsoft-system-center-endpoint-protection-supplemental-placeholder-eula.md
  sccm/core/misc/eula/microsoft-system-clr-types-for-microsoft-sql-server-2014.md
  sccm/core/misc/eula/sql-server-branded-components-included.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/core/plan-design/hierarchy/state-messaging-system-center-configuration-manager.md
  sccm/core/plan-design/hierarchy/use-a-cloud-based-distribution-point.md
  sccm/core/servers/deploy/configure/install-cloud-based-distribution-points-in-microsoft-azure.md
  sccm/mdm/deploy-use/management-tasks-applications.md
  sccm/osd/TOC.yml
  sccm/osd/deploy-use/scenarios-to-deploy-enterprise-operating-systems.md
  sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md
  sccm/osd/get-started/prepare-for-operating-system-deployment.md
  sccm/osd/understand/task-sequence-steps.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1266 Update automatically-deploy-software-updates.md
  sccm/sum/deploy-use/automatically-deploy-software-updates.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1277 From private repo
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md
  sccm/core/plan-design/hierarchy/state-messaging-system-center-configuration-manager.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1269 Update manage-drivers.md
  sccm/osd/get-started/manage-drivers.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1279 Fix SCCMDocs issue #1189
  sccm/core/servers/manage/list-of-reports.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1284 From private repo
  sccm/mdm/deploy-use/migrate-change-mdm-authority.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge
