Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2019-03, with the labels that each got.

#1293 From private repo
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/core/plan-design/hierarchy/log-files.md
  sccm/core/servers/deploy/install/release-notes.md
  sccm/core/servers/manage/checklist-for-installing-update-1810.md
  sccm/osd/TOC.yml
  sccm/osd/get-started/manage-boot-images.md
  sccm/osd/get-started/manage-drivers.md
  sccm/osd/understand/install-software-updates.md
  sccm/osd/understand/media/ts-step-install-software-updates.svg
  sccm/osd/understand/task-sequence-steps.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1297 Updated WSUS Maintenance URL
  sccm/sum/deploy-use/software-updates-maintenance.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1298 From private repo
  sccm/apps/deploy-use/create-applications.md
  sccm/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/sum/deploy-use/software-updates-maintenance.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1294 Update 1358333.md
  sccm/core/get-started/includes/1810/1358333.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1295 Update cloud-management-gateway-faq.md
  sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1304 From private repo
  sccm/comanage/how-to-prepare-Win10.md
  sccm/core/clients/deploy/deploy-clients-cmg-azure.md
  sccm/core/clients/manage/collections/create-collections.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/core/servers/deploy/install/release-notes.md
  sccm/core/understand/product-and-licensing-faq.md
  sccm/mdm/get-started/preparation-steps-for-on-premises-mdm.md
  sccm/mdm/get-started/set-up-intune-subscription-on-premises-mdm.md
  sccm/mdm/plan-design/plan-on-premises-mdm.md
  sccm/mdm/understand/manage-mobile-devices-with-on-premises-infrastructure.md
  sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1301 Task Sequences Service Window
  sccm/develop/reference/core/clients/sdk/ccm_servicewindow-client-wmi-class.md
Labels: ready-to-merge

#1300 In the UI, it say all deployment.
  sccm/develop/reference/core/clients/sdk/ccm_servicewindow-client-wmi-class.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1305 From private repo
  sccm/core/clients/manage/client-notification.md
  sccm/core/plan-design/configs/site-and-site-system-prerequisites.md
  sccm/core/servers/deploy/configure/high-availability-options.md
  sccm/core/servers/deploy/configure/use-a-sql-server-cluster-for-the-site-database.md
  sccm/core/servers/manage/admin-console.md
  sccm/core/support/support-center.md
  sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1309 From private repo
  sccm/comanage/toc.yml
  sccm/comanage/tutorial-co-manage-clients.md
  sccm/comanage/tutorial-co-manage-new-devices.md
  sccm/core/servers/deploy/install/use-the-setup-wizard-to-install-sites.md
  sccm/core/servers/manage/the-cd.latest-folder.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1311 Update toolkit-reference.md
  sccm/mdt/toolkit-reference.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1310 Update to line 42 missing link
  sccm/protect/deploy-use/endpoint-antimalware-policies.md
Labels: ready-to-merge

#1308 Update plan-cloud-management-gateway.md
  sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1302 Update certificates-for-cloud-management-gateway.md
  sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1312 From private repo
  sccm/core/misc/in-console-documentation.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1320 From private repo
  sccm/apps/deploy-use/create-deploy-scripts.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/core/plan-design/configs/site-and-site-system-prerequisites.md
  sccm/core/plan-design/hierarchy/log-files.md
  sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md
  sccm/mdm/deploy-use/create-mdm-collection.md
  sccm/mdm/deploy-use/manage-access-to-o365-services-for-pcs-managed-by-sccm.md
  sccm/mdm/deploy-use/manage-dynamics-crm-online-access.md
  sccm/mdm/deploy-use/manage-email-access.md
  sccm/mdm/deploy-use/manage-sharepoint-online-access.md
  sccm/mdm/deploy-use/manage-skype-for-business-online-access.md
  sccm/mdm/understand/whats-new-hybrid-archive.md
  sccm/sum/deploy-use/manage-office-365-proplus-updates.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1325 From private repo
  sccm/apps/deploy-use/create-deploy-scripts.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1328 Update certificates-for-cloud-management-gateway.md
  sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge, ready-to-merge

#1329 Update plan-cloud-management-gateway.md
  sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge, ready-to-merge

#1321 Minor Edits the Administration service section
  sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge, ready-to-merge

#1333 Update azure-template.md
  sccm/core/get-started/azure-template.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge, ready-to-merge

#1336 From private repo
  sccm/core/clients/manage/client-notification.md
  sccm/core/plan-design/changes/whats-new-in-version-1602.md
  sccm/desktop-analytics/enable-data-sharing.md
  sccm/desktop-analytics/tutorial-office-365.md
  sccm/mdm/TOC.yml
  sccm/mdm/deploy-use/device-compliance-policies.md
  sccm/mdm/deploy-use/manage-access-to-o365-services-for-pcs-managed-by-sccm.md
  sccm/mdm/deploy-use/manage-access-to-services.md
  sccm/mdm/deploy-use/manage-email-access.md
  sccm/mdm/understand/whats-new-hybrid-archive.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
  sccm/sum/get-started/install-a-software-update-point.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1342 From private repo
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/core/servers/manage/backup-and-recovery.md
  sccm/osd/deploy-use/manage-windows-as-a-service.md
  sccm/sum/deploy-use/add-software-updates-to-an-update-group.md
  sccm/sum/deploy-use/software-updates-maintenance.md
  sccm/sum/get-started/install-a-software-update-point.md
  sccm/sum/plan-design/plan-for-software-updates.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1346 From private repo
  sccm/core/clients/deploy/about-client-settings.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/core/plan-design/hierarchy/the-content-library.md
  sccm/core/servers/deploy/configure/site-server-high-availability.md
  sccm/desktop-analytics/tutorial-office-365.md
  sccm/sum/plan-design/plan-for-software-updates.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1341 Update set-up.md
  sccm/desktop-analytics/set-up.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1348 From private repo
  sccm/desktop-analytics/tutorial-office-365.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1357 From private repo
  sccm/protect/deploy-use/create-deploy-application-guard-policy.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1350 Update client-notification.md
  sccm/core/clients/manage/client-notification.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1351 Update about-client-settings.md
  sccm/core/clients/deploy/about-client-settings.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1353 Update use-a-sql-server-cluster-for-the-site-database.md
  sccm/core/servers/deploy/configure/use-a-sql-server-cluster-for-the-site-database.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1363 From private repo
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/sum/deploy-use/uup-preview.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1367 Exclude contents under includes folder
  sccm/docfx.json
Labels: Change sent to author, do-not-merge

#1369 From private repo
  sccm/core/clients/deploy/about-client-installation-properties.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1370 Update to Line 170 clarifying language
  sccm/protect/deploy-use/endpoint-antimalware-policies.md
Labels: Change sent to author, configmgr-protect/tech, configuration-manager/prod, ready-to-merge

#1377 From private repo
  sccm/apps/get-started/creating-linux-and-unix-server-applications.md
  sccm/apps/pcm/package-conversion-manager.md
  sccm/core/TOC.yml
  sccm/core/clients/deploy/deploy-clients-to-unix-and-linux-servers.md
  sccm/core/clients/deploy/linux-and-unix-clients-technical-reference.md
  sccm/core/clients/deploy/plan/planning-for-client-deployment-to-linux-and-unix-computers.md
  sccm/core/clients/manage/inventory/hardware-inventory-for-linux-and-unix.md
  sccm/core/clients/manage/manage-clients-for-linux-and-unix-servers.md
  sccm/core/clients/manage/monitor-clients-for-linux-and-unix-servers.md
  sccm/core/clients/manage/upgrade/upgrade-clients-for-linux-and-unix-servers.md
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-client.md
  sccm/core/plan-design/changes/media/3599209-client-health-dashboard.png
  sccm/core/plan-design/changes/media/3747129-installation-progress.png
  sccm/core/plan-design/changes/what-has-changed-from-configuration-manager-2012.md
  sccm/core/plan-design/changes/whats-new-in-version-1902.md
  sccm/core/plan-design/changes/whats-new-incremental-versions.md
  sccm/core/plan-design/configs/support-for-windows-10.md
  sccm/core/plan-design/diagnostics/levels-of-diagnostic-usage-data-collection-1902.md
  sccm/core/plan-design/hierarchy/the-content-library.md
  sccm/core/servers/deploy/configure/site-server-high-availability.md
  sccm/core/servers/deploy/install/list-of-prerequisite-checks.md
  sccm/core/servers/deploy/install/release-notes.md
  sccm/core/servers/deploy/install/upgrade-to-configuration-manager.md
  sccm/core/servers/manage/checklist-for-installing-update-1902.md
  sccm/core/servers/manage/cmpivot-tsg.md
  sccm/core/servers/manage/cmpivot.md
  sccm/core/servers/manage/current-branch-versions-supported.md
  sccm/core/servers/manage/install-in-console-updates.md
  sccm/core/servers/manage/media/1359068-cmpivot-barchart.png
  sccm/core/servers/manage/media/1359068-cmpivot-inventory.png
  sccm/core/servers/manage/media/1359068-cmpivot-piechart.png
  sccm/core/servers/manage/media/1359068-cmpivot-timechart.png
  sccm/core/servers/manage/media/CM_Servicing_support_timeline1.png
  sccm/core/servers/manage/media/cmpivot-audit-status-message.png
  sccm/core/servers/manage/media/cmpivot-clientoperationid.png
  sccm/core/servers/manage/media/cmpivot-favorite.png
  sccm/core/servers/manage/media/cmpivot-underlined-entities.png
  sccm/core/servers/manage/updates.md
  sccm/core/understand/accessibility-features.md
  sccm/core/understand/interoperability-client.md
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
  sccm/sum/deploy-use/integrate-windows-update-for-business-windows-10.md
  sccm/sum/deploy-use/software-updates-maintenance.md
  sccm/sum/get-started/install-a-software-update-point.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge
