Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2019-11, with the labels that each got.

#1972 Added Aaron's comment about underscored report names during update.
  sccm/core/servers/manage/best-practices-for-reporting.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge, triaged

#1983 From private repo
  sccm/core/get-started/2019/includes/1909/5410930.md
  sccm/core/get-started/2019/includes/1910/4488272.md
  sccm/desktop-analytics/connect-configmgr.md
  sccm/desktop-analytics/monitor-connection-health.md
  sccm/osd/deploy-use/manage-windows-as-a-service.md
  sccm/osd/understand/task-sequence-steps.md
  sccm/sum/deploy-use/manage-express-installation-files-for-windows-10-updates.md
  sccm/sum/get-started/configure-classifications-and-products.md
Labels: do-not-merge

#1847 Update supported OS of CmRcViewer.exe
  sccm/core/clients/manage/remote-control/remotely-administer-a-windows-client-computer.md
Labels: Change sent to author, assessing_(C&L), configmgr-client/tech, configuration-manager/prod, ready-to-merge

#1985 From private repo
  sccm/core/TOC.yml
  sccm/core/get-started/2019/includes/1911/4960084.md
  sccm/core/get-started/2019/includes/1911/5032900.md
  sccm/core/get-started/2019/media/4960084-endpoint-manager-logo.png
  sccm/core/get-started/2019/technical-preview-1907.md
  sccm/core/get-started/2019/technical-preview-1911.md
  sccm/core/get-started/technical-preview.md
  sccm/core/servers/manage/service-windows.md
  sccm/index.yml
  sccm/sum/deploy-use/office-365-dashboard.md
Labels: do-not-merge

#1987 From private repo
  sccm/core/get-started/capabilities-in-technical-preview-1802.md
  sccm/core/plan-design/hierarchy/accounts.md
  sccm/core/servers/deploy/configure/azure-services-wizard.md
  sccm/core/servers/manage/modify-your-infrastructure.md
  sccm/desktop-analytics/enroll-devices.md
  sccm/desktop-analytics/faq.md
  sccm/develop/core/understand/configuration-manager-sdk-samples.md
  sccm/mdm/deploy-use/protect-apps-using-mam-policies.md
  sccm/mdt/troubleshooting-reference.md
Labels: do-not-merge

#1991 From private repo
  sccm/core/clients/manage/client-notification.md
  sccm/core/get-started/2019/includes/1910/4488272.md
  sccm/core/get-started/2019/includes/1911/5032900.md
  sccm/core/get-started/2019/media/4488272-office-365-pro-plus-pilot.png
  sccm/core/misc/online-documentation.md
  sccm/index.yml
  sccm/sum/tools/updates-publisher.md
  template.md
Labels: do-not-merge

#1992 From private repo
  sccm/core/misc/in-console-documentation.md
  sccm/core/servers/deploy/configure/configure-role-based-administration.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#1993 Current SQL Server versions create more than one temp file
  sccm/core/understand/site-size-performance-faq.md
Labels: Change sent to author, assessing_(C&L), configuration-manager/prod, ready-to-merge

#1995 From private repo
  sccm/sum/deploy-use/uup-preview.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#1997 Update triggerschedule-method-in-class-sms_client.md
  sccm/develop/reference/core/clients/client-classes/triggerschedule-method-in-class-sms_client.md
Labels: Change sent to author, assessing_(C&L), configmgr-sdk/tech, configuration-manager/prod, ready-to-merge

#1998 Corrected Spelling
  sccm/desktop-analytics/enable-data-sharing.md
Labels: do-not-merge

#2001 From private repo
  sccm/sum/deploy-use/uup-preview.md
  sccm/sum/get-started/configure-classifications-and-products.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#2005 From private repo
  sccm/sum/get-started/configure-classifications-and-products.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#2004 need to add the \ to the directory paths
  sccm/mdt/sccm-guide.md
Labels: Change sent to author, configmgr-osd/tech, configuration-manager/prod, ready-to-merge

#2015 From private repo
  sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md
  sccm/osd/understand/task-sequence-steps.md
Labels: Change sent to author, configmgr-osd/tech, configuration-manager/prod, do-not-merge

#2014 change from def updates to security updates
  sccm/protect/deploy-use/endpoint-definition-updates.md
  sccm/protect/deploy-use/endpoint-definitions-microsoft-updates.md
  sccm/protect/deploy-use/endpoint-definitions-network.md
Labels: Change sent to author, assessing_(C&L), configmgr-protect/tech, configuration-manager/prod, ready-to-merge

#2017 From private repo
  sccm/sum/deploy-use/uup-preview.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#2020 From private repo
  sccm/core/plan-design/hierarchy/ports.md
  sccm/desktop-analytics/deploy-pilot.md
  sccm/sum/deploy-use/third-party-software-updates.md
  sccm/sum/get-started/configure-classifications-and-products.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#2023 From private repo
  sccm/core/plan-design/configs/site-and-site-system-prerequisites.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2024 Update about-client-settings.md
  sccm/core/clients/deploy/about-client-settings.md
Labels: Change sent to author, configmgr-client/tech, configuration-manager/prod, do-not-merge

#2035 From private repo
  sccm/apps/deploy-use/learn-script-security.md
  sccm/core/plan-design/changes/whats-new-in-version-1906.md
  sccm/core/servers/manage/pre-release-features.md
  sccm/protect/TOC.yml
  sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md
Labels: do-not-merge
