Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2019-10, with the labels that each got.

#1914 Typo "Asure" > "Azure"
  sccm/develop/reference/core/servers/configure/sms_azureservice-server-wmi-class.md
Labels: Change sent to author, configmgr-sdk/tech, configuration-manager/prod, do-not-merge

#1916 From private repo
  sccm/comanage/tutorial-co-manage-new-devices.md
  sccm/core/clients/manage/upgrade/upgrade-clients-on-mac-computers.md
  sccm/core/get-started/2019/includes/1909/3098816.md
  sccm/core/get-started/2019/includes/1909/4488301.md
  sccm/core/get-started/2019/includes/1909/5012536.md
  sccm/core/get-started/2019/includes/1909/known-issue-hinv.md
  sccm/core/get-started/2019/media/4488301-o365-health.png
  sccm/core/get-started/2019/technical-preview-1909.md
  sccm/core/get-started/capabilities-in-technical-preview-1705.md
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md
  sccm/core/plan-design/changes/whats-new-in-version-1906.md
  sccm/core/plan-design/configs/support-for-windows-10.md
  sccm/core/plan-design/configs/supported-configurations.md
  sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md
  sccm/core/plan-design/hierarchy/ports.md
  sccm/core/servers/deploy/configure/azure-services-wizard.md
  sccm/desktop-analytics/faq.md
  sccm/mdm/deploy-use/migrate-prepare-intune.md
  sccm/mdm/understand/whats-new-hybrid-archive.md
  sccm/osd/deploy-use/configure-precache-content.md
  sccm/protect/deploy-use/create-deploy-exploit-guard-policy.md
  sccm/protect/deploy-use/troubleshoot-endpoint-client.md
  sccm/sum/deploy-use/uup-preview.md
  sccm/sum/get-started/configure-classifications-and-products.md
Labels: do-not-merge

#1917 testing PRMerger automation
  sccm/core/misc/online-documentation.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#1910 Update to include CMPowerLogViewer
  sccm/core/support/support-center-onetrace.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, do-not-merge

#1920 From private repo
  sccm/core/plan-design/changes/whats-new-in-version-1802.md
  sccm/desktop-analytics/faq.md
  sccm/desktop-analytics/whats-new.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#1923 From private repo
  sccm/core/servers/manage/cmpivot-tsg.md
  sccm/desktop-analytics/enable-data-sharing.md
  sccm/desktop-analytics/tutorial-windows10.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#1926 From private repo
  sccm/desktop-analytics/overview.md
  sccm/sum/deploy-use/software-updates-maintenance.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#1927 Update use-a-pull-distribution-point.md
  sccm/core/plan-design/hierarchy/use-a-pull-distribution-point.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#1930 From private repo
  sccm/core/clients/manage/monitor-windows-analytics.md
  sccm/core/clients/manage/upgrade-readiness.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md
  sccm/desktop-analytics/about-assets.md
  sccm/desktop-analytics/about-deployment-plans.md
  sccm/desktop-analytics/about-updates.md
  sccm/desktop-analytics/account-close.md
  sccm/desktop-analytics/account-reset.md
  sccm/desktop-analytics/compat-assessment.md
  sccm/desktop-analytics/connect-configmgr.md
  sccm/desktop-analytics/create-deployment-plans.md
  sccm/desktop-analytics/deploy-pilot.md
  sccm/desktop-analytics/deploy-prod.md
  sccm/desktop-analytics/enable-data-sharing.md
  sccm/desktop-analytics/enroll-devices.md
  sccm/desktop-analytics/faq.md
  sccm/desktop-analytics/get-support.md
  sccm/desktop-analytics/health-status-monitoring.md
  sccm/desktop-analytics/overview.md
  sccm/desktop-analytics/privacy.md
  sccm/desktop-analytics/set-up.md
  sccm/desktop-analytics/toc.yml
  sccm/desktop-analytics/tutorial-windows10.md
  sccm/desktop-analytics/whats-new.md
Labels: do-not-merge

#1939 From private repo
  sccm/osd/understand/task-sequence-steps.md
  sccm/osd/understand/task-sequence-variables.md
Labels: Change sent to author, configmgr-osd/tech, configuration-manager/prod, do-not-merge

#1937 Incorrect Windows Insider CUs Info
  sccm/sum/get-started/configure-classifications-and-products.md
Labels: Change sent to author, assessing_(C&L), configmgr-sum/tech, configuration-manager/prod, ready-to-merge

#1938 Removed gendering
  sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md
Labels: Change sent to author, assessing_(C&L), configmgr-sum/tech, configuration-manager/prod, ready-to-merge

#1945 From private repo
  sccm/core/plan-design/configs/support-for-windows-10.md
  sccm/desktop-analytics/enable-data-sharing.md
  sccm/desktop-analytics/faq.md
  sccm/desktop-analytics/ready-for-windows.md
  sccm/mdt/use-the-mdt.md
  sccm/mdt/user-driven-installation-developers-guide.md
  sccm/sum/plan-design/plan-for-software-updates.md
Labels: do-not-merge

#1949 From private repo
  sccm/core/TOC.yml
  sccm/core/get-started/2019/includes/1910/3556011.md
  sccm/core/get-started/2019/includes/1910/3608345.md
  sccm/core/get-started/2019/includes/1910/4433455.md
  sccm/core/get-started/2019/includes/1910/4488272.md
  sccm/core/get-started/2019/includes/1910/4561024.md
  sccm/core/get-started/2019/includes/1910/4640570.md
  sccm/core/get-started/2019/includes/1910/4680263.md
  sccm/core/get-started/2019/includes/1910/4737447.md
  sccm/core/get-started/2019/includes/1910/4760058.md
  sccm/core/get-started/2019/includes/1910/4786915.md
  sccm/core/get-started/2019/includes/1910/known-issue-osd.md
  sccm/core/get-started/2019/media/3556011-feedback-add-files.png
  sccm/core/get-started/2019/media/3608345-configuration-baseline-properties.png
  sccm/core/get-started/2019/media/3608345-create-compliance-policy-rule.png
  sccm/core/get-started/2019/media/4488272-office-365-pro-plus-pilot.png
  sccm/core/get-started/2019/media/4561024-create-microsoft-edge-application.png
  sccm/core/get-started/2019/media/4561024-edge-settings-wizard.png
  sccm/core/get-started/2019/media/4561024-software-center-install-edge.png
  sccm/core/get-started/2019/media/4640570-search-too-many-results.png
  sccm/core/get-started/2019/technical-preview-1906.md
  sccm/core/get-started/2019/technical-preview-1910.md
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/hierarchy/accounts.md
Labels: do-not-merge

#1940 More possible values for OfferFlags property
  sccm/develop/reference/apps/sms_applicationassignment-server-wmi-class.md
Labels: Change sent to author, assessing_(C&L), configmgr-sdk/tech, configuration-manager/prod, ready-to-merge

#1942 Detail OS applicability of registry values CommercialId and AllowTelemetry
  sccm/desktop-analytics/enroll-devices.md
  sccm/desktop-analytics/log-collector.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#1944 Changed "managed virtual machines" to "managed systems" in Cloud Prot…
  sccm/protect/deploy-use/endpoint-antimalware-policies.md
Labels: Change sent to author, assessing_(C&L), configmgr-protect/tech, configuration-manager/prod, ready-to-merge

#1947 Updated requirements and download links
  sccm/desktop-analytics/log-collector.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#1948 Updated endpoint details
  sccm/desktop-analytics/enable-data-sharing.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#1912 Update manage-windows-as-a-service.md
  sccm/osd/deploy-use/manage-windows-as-a-service.md
Labels: Change sent to author, assessing_(C&L), configmgr-sum/tech, configuration-manager/prod, ready-to-merge

#1954 From private repo
  sccm/core/plan-design/configs/support-for-active-directory-domains.md
  sccm/core/servers/deploy/install/list-of-prerequisite-checks.md
  sccm/core/understand/product-and-licensing-faq.md
  sccm/sum/deploy-use/office-365-dashboard.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#1951 Update software-updates-views-configuration-manager.md
  sccm/develop/core/understand/sqlviews/software-updates-views-configuration-manager.md
Labels: assessing_(C&L), ready-to-merge, review-team-triage

#1957 From private repo
  sccm/core/get-started/2019/includes/1910/3556011.md
  sccm/core/get-started/2019/includes/1910/3608345.md
  sccm/core/misc/in-console-documentation.md
  sccm/desktop-analytics/compat-assessment.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#1961 From private repo
  sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md
  sccm/sum/deploy-use/uup-preview.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#1967 From private repo
  sccm/core/misc/in-console-documentation.md
  sccm/core/plan-design/configs/support-for-windows-10.md
  sccm/desktop-analytics/enable-data-sharing.md
  sccm/sum/deploy-use/uup-preview.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#1962 Update sms_client-client-wmi-class.md
  sccm/develop/reference/core/clients/client-classes/sms_client-client-wmi-class.md
Labels: Change sent to author, assessing_(C&L), configmgr-sdk/tech, configuration-manager/prod, ready-to-merge

#1966 correct AD publishing option instructions
  sccm/core/clients/deploy/deploy-clients-to-windows-computers.md
Labels: Change sent to author, assessing_(C&L), configmgr-client/tech, configuration-manager/prod, ready-to-merge

#1974 From private repo
  sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md
  sccm/desktop-analytics/compat-assessment.md
  sccm/desktop-analytics/enable-data-sharing.md
  sccm/desktop-analytics/enroll-devices.md
  sccm/desktop-analytics/media/3594545-app-removed.png
  sccm/desktop-analytics/whats-new.md
  sccm/mdt/index.yml
Labels: do-not-merge

#1975 Spelling Correction
  sccm/osd/get-started/manage-user-state.md
Labels: Change sent to author, configmgr-osd/tech, configuration-manager/prod, do-not-merge

#1969 Removed v_UpdatePrograms reference.
  sccm/develop/core/understand/sqlviews/sample-queries-software-updates-configuration-manager.md
Labels: assessing_(C&L), ready-to-merge, review-team-triage

#1970 Include primary/secondary site comments on DP reassign
  sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge
