Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2019-01, with the labels that each got.

#1129 Update whats-new-in-version-1810.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1130 From private repo
  sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md
  sccm/core/clients/manage/upgrade/upgrade-clients.md
  sccm/core/plan-design/security/cryptographic-controls-technical-reference.md
  sccm/core/servers/deploy/configure/azure-services-wizard.md
  sccm/core/servers/deploy/install/release-notes.md
  sccm/mdm/deploy-use/migrate-hybridmdm-to-intunesa.md
  sccm/mdm/deploy-use/migrate-prepare-intune.md
  sccm/mdt/toolkit-reference.md
  sccm/osd/get-started/manage-operating-system-upgrade-packages.md
  sccm/osd/understand/task-sequence-steps.md
  sccm/sum/deploy-use/uup-preview.md
  sccm/sum/media/uup-preview-client-settings.png
Labels: do-not-merge

#1125 Update setup-cloud-management-gateway.md
  sccm/core/clients/manage/cmg/setup-cloud-management-gateway.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#854 Update upgrade-on-premises-infrastructure.md
  sccm/core/servers/manage/upgrade-on-premises-infrastructure.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1131 Update enhanced-http.md
  sccm/core/plan-design/hierarchy/enhanced-http.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1132 From private repo
  sccm/core/understand/frequently-asked-questions-about-diagnostics-and-usage-data.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1138 From private repo
  sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md
  sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md
  sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md
  sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1139 Update enhanced-http.md
  sccm/core/plan-design/hierarchy/enhanced-http.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1140 From private repo
  sccm/sum/deploy-use/uup-preview.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1141 Client Notification from Devices node
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1149 From private repo
  sccm/core/get-started/includes/1810-2/1357013.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md
  sccm/core/plan-design/changes/what-has-changed-from-configuration-manager-2012.md
  sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md
  sccm/index.md
  sccm/mdm/deploy-use/windows-hello-for-business-settings.md
  sccm/protect/deploy-use/windows-hello-for-business-settings.md
  sccm/protect/understand/protect-data-and-site-infrastructure.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1151 From private repo
  sccm/core/plan-design/configs/support-for-virtualization-environments.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1157 From private repo
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1165 From private repo
  sccm/core/clients/manage/inventory/extend-hardware-inventory.md
  sccm/core/clients/manage/remote-control/remotely-administer-a-windows-client-computer.md
  sccm/core/get-started/capabilities-in-technical-preview-1703.md
  sccm/core/misc/in-console-documentation.md
  sccm/core/servers/deploy/install/language-packs.md
  sccm/core/servers/manage/creating-custom-report-models-in-sql-server-reporting-services.md
  sccm/mdm/deploy-use/configure-ios-apps-with-app-configuration-policies.md
  sccm/mdm/deploy-use/create-configuration-items-for-ios-and-mac-os-x-devices-managed-without-the-client.md
  sccm/osd/deploy-use/manage-task-sequences-to-automate-tasks.md
  sccm/protect/deploy-use/certificate-infrastructure.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1145 Update manually-deploy-software-updates.md
  sccm/sum/deploy-use/manually-deploy-software-updates.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1147 Update automatically-deploy-software-updates.md
  sccm/sum/deploy-use/automatically-deploy-software-updates.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1159 Update fundamental-concepts-for-content-management.md
  sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge, ready-to-merge

#1156 Update migrate-prepare-intune.md
  sccm/mdm/deploy-use/migrate-prepare-intune.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1158 Update task-sequence-variables.md
  sccm/osd/understand/task-sequence-variables.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1152 Sec role doesn't exist in CM; make it clearer. :-)
  sccm/core/servers/manage/cmpivot.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1167 From private repo
  sccm/comanage/overview.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-client.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-server.md
  sccm/core/plan-design/configs/site-and-site-system-prerequisites.md
  sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1172 From private repo
  sccm/index.md
Labels: Change sent to author, do-not-merge

#1175 Added a missing space, purely a formatting fix.
  sccm/core/clients/deploy/windows-firewall-and-port-settings-for-clients.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1183 From private repo
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1186 Update data-warehouse.md
  sccm/core/servers/manage/data-warehouse.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1195 From private repo
  sccm/core/plan-design/hierarchy/ports.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1171 Correct permissions to the web app
  sccm/core/clients/manage/upgrade-readiness.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1205 Update plan-internet-based-client-management.md
  sccm/core/clients/manage/plan-internet-based-client-management.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1161 Update manage-office-365-proplus-updates.md
  sccm/sum/deploy-use/manage-office-365-proplus-updates.md
Labels: Change sent to author, configuration-manager/prod, ready-to-merge

#1210 From private repo
  sccm/comanage/quickstart-remote-actions.md
  sccm/core/misc/eula/third-party-notices.md
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/plan-design/changes/whats-new-in-version-1810.md
  sccm/desktop-analytics/about-assets.md
  sccm/desktop-analytics/about-deployment-plans.md
  sccm/desktop-analytics/about-updates.md
  sccm/desktop-analytics/app-health-analyzer.md
  sccm/desktop-analytics/compat-risk.md
  sccm/desktop-analytics/connect-configmgr.md
  sccm/desktop-analytics/create-deployment-plans.md
  sccm/desktop-analytics/deploy-pilot.md
  sccm/desktop-analytics/deploy-prod.md
  sccm/desktop-analytics/enable-data-sharing.md
  sccm/desktop-analytics/enroll-devices.md
  sccm/desktop-analytics/health-status-monitoring.md
  sccm/desktop-analytics/includes/define-pilot-prod.md
  sccm/desktop-analytics/media/aha-app-confidence-simulation.png
  sccm/desktop-analytics/media/aha-desktop-analytics-compat-risk-factors.png
  sccm/desktop-analytics/media/aha-risk-assessment-engine.png
  sccm/desktop-analytics/media/app-readiness-report-evaluating.png
  sccm/desktop-analytics/media/available-functionality.png
  sccm/desktop-analytics/media/commercial-id.png
  sccm/desktop-analytics/media/connection-health-dashboard.png
  sccm/desktop-analytics/media/da-data-flow-v1.png
  sccm/desktop-analytics/media/deployment-plan-overview.png
  sccm/desktop-analytics/media/diagnostic-data-levels.png
  sccm/desktop-analytics/media/feature-updates.png
  sccm/desktop-analytics/media/monitor-health-status-factors.png
  sccm/desktop-analytics/media/monitor-health.png
  sccm/desktop-analytics/media/office-add-in-health-status-factors.png
  sccm/desktop-analytics/media/office-macros-health-status-factors.png
  sccm/desktop-analytics/media/portal-home.png
  sccm/desktop-analytics/media/prep-prod-set-upgrade-decision.png
  sccm/desktop-analytics/media/prepare-production.png
  sccm/desktop-analytics/media/prod-deployment-status.png
  sccm/desktop-analytics/media/sccm-device-list-properly-enrolled.png
  sccm/desktop-analytics/media/security-updates.png
  sccm/desktop-analytics/media/unknown-device-name.png
  sccm/desktop-analytics/media/wa-data-flow-v1.png
  sccm/desktop-analytics/overview.md
  sccm/desktop-analytics/privacy.md
  sccm/desktop-analytics/set-up.md
  sccm/desktop-analytics/toc.yml
  sccm/desktop-analytics/troubleshooting.md
  sccm/desktop-analytics/tutorial-office-365.md
  sccm/docfx.json
  sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md
  sccm/mdt/release-notes.md
  sccm/sum/deploy-use/uup-preview.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1213 From private repo
  sccm/core/servers/deploy/install/prerequisites-for-installing-sites.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge

#1215 From private repo
  sccm/compliance/plan-design/scap/about-scap.md
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/plan-design/hierarchy/ports.md
  sccm/core/servers/manage/pre-release-features.md
  sccm/core/support/support-center.md
  sccm/sum/deploy-use/uup-preview.md
Labels: Change sent to author, configuration-manager/prod, do-not-merge
