Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2020-03, with the labels that each got.

#2235 From private repo
  sccm/core/TOC.yml
  sccm/core/get-started/2020/includes/2002-2/3555758.md
  sccm/core/get-started/2020/includes/2002-2/3696246.md
  sccm/core/get-started/2020/includes/2002-2/5834830.md
  sccm/core/get-started/2020/includes/2002-2/5891241.md
  sccm/core/get-started/2020/includes/2002-2/5907383.md
  sccm/core/get-started/2020/includes/2002-2/5925660.md
  sccm/core/get-started/2020/includes/2002-2/5954175.md
  sccm/core/get-started/2020/includes/2002-2/6268489.md
  sccm/core/get-started/2020/includes/2002-2/6307931.md
  sccm/core/get-started/2020/media/5891241-ci-node-search-all-subfolders.png
  sccm/core/get-started/2020/technical-preview-2002-2.md
  sccm/core/get-started/technical-preview.md
  sccm/core/misc/user-experience-analytics-preview.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2162 Update deploy-edge.md to note that the content location for the application must be empty when using the wizard to create the application.
  sccm/apps/deploy-use/deploy-edge.md
Labels: Change sent to author, aq-pr-triaged, configmgr-app/tech, configuration-manager/prod, ready-to-merge

#2236 Tweak to recommended software/AP
  sccm/core/misc/user-experience-analytics-preview.md
Labels: Change sent to author, aq-pr-triaged, configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2205 Update manage-windows-as-a-service.md
  sccm/osd/deploy-use/manage-windows-as-a-service.md
Labels: Change sent to author, aq-pr-triaged, configmgr-sum/tech, configuration-manager/prod, ready-to-merge

#2238 From private repo
  sccm/apps/deploy-use/deploy-edge.md
Labels: Change sent to author, configmgr-app/tech, configuration-manager/prod, do-not-merge

#2239 added some changes to make it clearer
  sccm/core/get-started/2020/includes/2002-2/6268489.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2241 From private repo
  sccm/comanage/overview.md
Labels: Change sent to author, configmgr-client/tech, configuration-manager/prod, do-not-merge

#2219 Don't need to use Download all content locally with 1910
  sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md
Labels: Change sent to author, aq-pr-triaged, configmgr-client/tech, configuration-manager/prod, ready-to-merge

#2247 Eliminate confusion on OSDKeepActivation
  sccm/osd/understand/task-sequence-variables.md
Labels: Change sent to author, aq-pr-triaged, configmgr-osd/tech, configuration-manager/prod, ready-to-merge

#2250 Correct linked URLs and poor wording
  sccm/develop/reference/osd/sms_tasksequence_prepareosaction-server-wmi-class.md
Labels: Change sent to author, aq-pr-triaged, configmgr-sdk/tech, configuration-manager/prod, ready-to-merge

#2253 From private repo
  sccm/apps/get-started/creating-windows-applications.md
  sccm/core/get-started/2020/includes/2002-2/3555758.md
  sccm/core/get-started/2020/media/3555758-all-devices.png
  sccm/core/get-started/2020/media/3555758-comanagement-wizard.png
  sccm/core/get-started/2020/media/3555758-configure-upload.png
  sccm/core/get-started/2020/media/3555758-device-overview-actions.png
  sccm/core/get-started/2020/technical-preview-2002-2.md
  sccm/core/get-started/set-up-your-lab.md
  sccm/core/misc/mms2019docathon.md
  sccm/core/plan-design/choose-a-device-management-solution.md
  sccm/core/understand/use-docs.md
  sccm/desktop-analytics/compat-assessment.md
  sccm/desktop-analytics/deploy-pilot.md
  sccm/desktop-analytics/media/5746559-safeguards.png
  sccm/desktop-analytics/overview.md
  sccm/desktop-analytics/ready-for-windows.md
  sccm/desktop-analytics/whats-new.md
Labels: do-not-merge

#2254 From private repo
  sccm/core/get-started/2020/includes/2001/3871913.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2255 minor grammar changes
  sccm/comanage/tutorial-co-manage-clients.md
Labels: Change sent to author, configmgr-client/tech, configuration-manager/prod, do-not-merge

#2257 From private repo
  sccm/core/misc/user-experience-analytics-preview.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2270 From private repo
  sccm/comanage/includes/enable-co-management-1906-and-higher.md
  sccm/comanage/tutorial-co-manage-clients.md
  sccm/comanage/tutorial-co-manage-new-devices.md
  sccm/core/get-started/2020/includes/2002-2/3555758.md
  sccm/core/misc/in-console-documentation.md
  sccm/core/servers/manage/reference-for-maintenance-tasks.md
  sccm/desktop-analytics/compat-assessment.md
  sccm/desktop-analytics/connect-configmgr.md
  sccm/desktop-analytics/create-deployment-plans.md
  sccm/desktop-analytics/deploy-pilot.md
  sccm/desktop-analytics/enable-data-sharing.md
  sccm/desktop-analytics/overview.md
  sccm/desktop-analytics/whats-new.md
Labels: do-not-merge

#2272 From private repo
  sccm/core/plan-design/hierarchy/state-messaging-system-center-configuration-manager.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2269 Fix Markdown layout + malformatted quotes
  sccm/develop/reference/osd/sms_tasksequence_enablebitlockeraction-server-wmi-class.md
Labels: Change sent to author, aq-pr-triaged, configmgr-sdk/tech, configuration-manager/prod, ready-to-merge

#2273 From private repo
  sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md
  sccm/core/clients/manage/collections/create-collections.md
  sccm/core/misc/in-console-documentation.md
  sccm/core/plan-design/changes/whats-new-in-version-1910.md
  sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md
  sccm/core/plan-design/hierarchy/client-peer-cache.md
  sccm/osd/deploy-use/create-bootable-media.md
  sccm/osd/deploy-use/create-prestaged-media.md
  sccm/protect/deploy-use/bitlocker/setup-websites.md
  sccm/protect/deploy-use/endpoint-protection.md
Labels: Change sent to author, configmgr-protect/tech, configuration-manager/prod, do-not-merge

#2274 From private repo
  sccm/core/misc/user-experience-analytics-preview.md
  sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md
  sccm/core/understand/product-and-licensing-faq.md
  sccm/develop/core/servers/configure/how-to-create-a-program.md
  sccm/osd/deploy-use/manage-task-sequences-to-automate-tasks.md
  sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md
Labels: Change sent to author, configmgr-osd/tech, configuration-manager/prod, do-not-merge

#2278 From private repo
  sccm/desktop-analytics/create-deployment-plans.md
  sccm/desktop-analytics/deploy-pilot.md
  sccm/desktop-analytics/whats-new.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2285 From private repo
  sccm/core/clients/deploy/configure-wake-on-lan.md
  sccm/core/misc/media/dataflow.png
  sccm/core/misc/media/overview-page.png
  sccm/core/misc/media/proactive-remediations-create.png
  sccm/core/misc/media/proactive-remediations-device-status.png
  sccm/core/misc/media/proactive-remediations-report-overview.png
  sccm/core/misc/media/proactive-remediations-script-settings.png
  sccm/core/misc/media/recommended-software.png
  sccm/core/misc/media/settings-baseline.png
  sccm/core/misc/media/settings-general.png
  sccm/core/misc/media/startup-performance.png
  sccm/core/misc/media/uea-overview-page.png
  sccm/core/misc/media/uea-proactive-remediations-create.png
  sccm/core/misc/media/uea-proactive-remediations-device-status.png
  sccm/core/misc/media/uea-proactive-remediations-report-overview.png
  sccm/core/misc/media/uea-proactive-remediations-script-settings.png
  sccm/core/misc/media/uea-recommended-software.png
  sccm/core/misc/media/uea-settings-baseline.png
  sccm/core/misc/media/uea-settings-general.png
  sccm/core/misc/user-experience-analytics-preview.md
  sccm/core/misc/whats-new-endpoint-analytics.md
  sccm/sum/get-started/install-a-software-update-point.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#2280 Update connect-configmgr.md
  sccm/desktop-analytics/connect-configmgr.md
Labels: Change sent to author, aq-pr-triaged, configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2284 Update enhanced-http.md
  sccm/core/plan-design/hierarchy/enhanced-http.md
Labels: Change sent to author, aq-pr-triaged, configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2281 Update technical-preview.md
  sccm/core/get-started/technical-preview.md
Labels: Change sent to author, aq-pr-triaged, configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2287 From private repo
  sccm/core/plan-design/hierarchy/enhanced-http.md
  sccm/core/servers/manage/reference-for-maintenance-tasks.md
  sccm/sum/get-started/manage-settings-for-software-updates.md
Labels: do-not-merge
