Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2020-01, with the labels that each got.

#2115 From private repo
  sccm/compliance/deploy-use/create-configuration-items-for-windows-10-devices-managed-with-the-client.md
  sccm/core/servers/manage/backup-and-recovery.md
  sccm/mdm/deploy-use/create-configuration-items-for-windows-8.1-and-windows-10-devices-managed-without-the-client.md
Labels: Change sent to author, configmgr-hybrid/tech, configuration-manager/prod, do-not-merge

#2118 From private repo
  sccm/sum/TOC.yml
  sccm/sum/index.yml
Labels: do-not-merge, review-team-triage

#2123 From private repo
  sccm/protect/TOC.yml
  sccm/protect/index.yml
  sccm/sum/deploy-use/software-updates-maintenance.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#2127 From private repo
  sccm/core/clients/manage/manage-clients.md
  sccm/core/servers/deploy/install/prerequisite-checker.md
  sccm/desktop-analytics/about-deployment-plans.md
Labels: do-not-merge

#2110 Extended CIType_ID with Types from SCCM 1906
  sccm/develop/reference/compliance/sms_configurationitemlatestbaseclass-server-wmi-class.md
Labels: Change sent to author, assessing_(C&L), configmgr-sdk/tech, configuration-manager/prod, ready-to-merge

#2111 Extended RelationType with Types from SCCM 1906
  sccm/develop/reference/sum/sms_cirelation-server-wmi-class.md
Labels: Change sent to author, assessing_(C&L), configmgr-sdk/tech, configuration-manager/prod, ready-to-merge

#2130 From private repo
  sccm/core/misc/in-console-documentation.md
  sccm/core/servers/deploy/install/release-notes.md
  sccm/desktop-analytics/about-updates.md
  sccm/desktop-analytics/overview.md
  sccm/desktop-analytics/privacy.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2133 In the Back up certificate SQL script, removed END
  sccm/protect/deploy-use/bitlocker/encrypt-recovery-data.md
Labels: Change sent to author, assessing_(C&L), configmgr-protect/tech, configuration-manager/prod, ready-to-merge

#2140 Add brackets to function prototype 'CategoryIds'
  sccm/develop/reference/core/servers/configure/addmemberships-method-in-class-sms_securedcategorymembership.md
Labels: Change sent to author, assessing_(C&L), configmgr-sdk/tech, configuration-manager/prod, ready-to-merge

#2143 From private repo
  sccm/desktop-analytics/overview.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2144 Update compat-assessment.md
  sccm/desktop-analytics/compat-assessment.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2148 Update create-deployment-plans.md
  sccm/desktop-analytics/create-deployment-plans.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2156 From private repo
  sccm/core/TOC.yml
  sccm/core/get-started/2019/technical-preview-1909.md
  sccm/core/get-started/2020/includes/2001/2356386.md
  sccm/core/get-started/2020/includes/2001/3098816.md
  sccm/core/get-started/2020/includes/2001/3721603.md
  sccm/core/get-started/2020/includes/2001/3871913.md
  sccm/core/get-started/2020/includes/2001/5559993.md
  sccm/core/get-started/2020/includes/2001/5728365.md
  sccm/core/get-started/2020/includes/2001/6005561.md
  sccm/core/get-started/2020/includes/2001/6030715.md
  sccm/core/get-started/2020/includes/feature-include-template.md
  sccm/core/get-started/2020/includes/known-issue-include-template.md
  sccm/core/get-started/2020/media/2356386-task-sequence-progress.png
  sccm/core/get-started/2020/media/3098816-orchestration-groups-site-code.png
  sccm/core/get-started/2020/media/3871913-microsoft-edge-dashboard.png
  sccm/core/get-started/2020/media/5559993-onetrace-log-groups.png
  sccm/core/get-started/2020/technical-preview-2001.md
  sccm/core/get-started/technical-preview.md
  sccm/core/plan-design/changes/whats-new-in-version-1910.md
  sccm/desktop-analytics/about-assets.md
  sccm/desktop-analytics/connect-configmgr.md
  sccm/desktop-analytics/deploy-pilot.md
  sccm/desktop-analytics/get-support.md
  sccm/desktop-analytics/health-status-monitoring.md
  sccm/desktop-analytics/media/5451636-portal-feedback.png
  sccm/desktop-analytics/whats-new.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#1913 Added section Setup Downloader on another computer
  sccm/core/servers/deploy/install/setup-downloader.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, do-not-merge

#2063 Added new step for Cryptography settings
  sccm/core/plan-design/network/example-deployment-of-pki-certificates.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2129 Updated key length to 4,096 for Cloud DP Cert
  sccm/core/plan-design/network/pki-certificate-requirements.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2141 Update deploy-edge.md
  sccm/apps/deploy-use/deploy-edge.md
Labels: Change sent to author, assessing_(C&L), configmgr-app/tech, configuration-manager/prod, ready-to-merge

#2160 Change "backslash" to "slash"
  sccm/core/clients/deploy/about-client-installation-properties.md
Labels: Change sent to author, configmgr-client/tech, configuration-manager/prod, ready-to-merge

#2057 Update optimize-windows-10-update-delivery.md
  sccm/sum/deploy-use/optimize-windows-10-update-delivery.md
Labels: Change sent to author, assessing_(C&L), configmgr-sum/tech, configuration-manager/prod, ready-to-merge

#2164 Update create-applications.md
  sccm/apps/deploy-use/create-applications.md
Labels: Change sent to author, configmgr-app/tech, configuration-manager/prod, ready-to-merge

#2169 Tweak wording for caveat from SCCMdocs/pull/2057
  sccm/sum/deploy-use/optimize-windows-10-update-delivery.md
Labels: do-not-merge

#2174 From private repo - Jan.30
  sccm/apps/TOC.yml
  sccm/apps/index.yml
  sccm/comanage/overview.md
  sccm/compliance/TOC.yml
  sccm/compliance/index.yml
  sccm/core/clients/deploy/deploy-clients-to-macs.md
  sccm/core/clients/manage/upgrade/upgrade-clients-on-mac-computers.md
  sccm/core/get-started/2020/includes/2001/6005561.md
  sccm/core/misc/media/uea-dataflow.png
  sccm/core/misc/media/uea-overview-page.png
  sccm/core/misc/media/uea-proactive-remediations-create.png
  sccm/core/misc/media/uea-proactive-remediations-device-status.png
  sccm/core/misc/media/uea-proactive-remediations-report-overview.png
  sccm/core/misc/media/uea-proactive-remediations-script-settings.png
  sccm/core/misc/media/uea-recommended-software.png
  sccm/core/misc/media/uea-settings-baseline.png
  sccm/core/misc/media/uea-settings-general.png
  sccm/core/misc/media/uea-startup-performance.png
  sccm/core/misc/user-experience-analytics-preview.md
  sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md
  sccm/core/servers/deploy/install/release-notes.md
  sccm/core/servers/deploy/install/setup-reference.md
  sccm/core/servers/deploy/install/use-the-setup-wizard-to-install-sites.md
  sccm/core/understand/product-and-licensing-faq.md
  sccm/desktop-analytics/compat-assessment.md
  sccm/desktop-analytics/faq.md
  sccm/desktop-analytics/index.yml
  sccm/desktop-analytics/toc.yml
  sccm/mdm/index.yml
  sccm/mdt/TOC.yml
  sccm/mdt/index.yml
  sccm/osd/TOC.yml
  sccm/osd/index.yml
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2175 multiple files: fix typos
  sccm/core/clients/deploy/about-client-settings.md
  sccm/core/get-started/2019/includes/1906/3976435.md
  sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md
  sccm/develop/core/servers/configure/how-to-assign-an-advertisement-to-a-collection-of-computers.md
  sccm/develop/core/servers/configure/how-to-create-an-advertisement.md
  sccm/develop/reference/core/servers/configure/readfromstring-method-in-class-sms_schedulemethods.md
  sccm/develop/reference/core/servers/configure/writetostring-method-in-class-sms_schedulemethods.md
  sccm/osd/deploy-use/install-new-windows-version-new-computer-bare-metal.md
  sccm/osd/get-started/manage-operating-system-upgrade-packages.md
  sccm/osd/understand/task-sequence-steps.md
  template.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2176 From private repo - Daily publishing Jan.31 am
  .openpublishing.redirection.json
  sccm/core/TOC.yml
  sccm/core/clients/deploy/about-client-settings.md
  sccm/core/clients/manage/monitor-windows-analytics.md
  sccm/core/clients/manage/upgrade-readiness.md
  sccm/core/get-started/capabilities-in-technical-preview-1703.md
  sccm/core/get-started/capabilities-in-technical-preview-1705.md
  sccm/core/get-started/capabilities-in-technical-preview-1706.md
  sccm/core/get-started/capabilities-in-technical-preview-1710.md
  sccm/core/index.yml
  sccm/core/misc/eula/microsoft-sql-server-2014-shared-management-objects.md
  sccm/core/misc/eula/microsoft-sql-server-compact-4.0-service-pack-1-sp1.md
  sccm/core/misc/eula/microsoft-system-center-configuration-manager-supplemental-hotfix.md
  sccm/core/misc/eula/microsoft-system-center-configuration-manager.md
  sccm/core/misc/eula/microsoft-system-center-endpoint-protection.md
  sccm/core/misc/eula/microsoft-system-clr-types-for-microsoft-sql-server-2014.md
  sccm/core/misc/user-experience-analytics-preview.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md
  sccm/core/plan-design/changes/whats-new-in-version-1706.md
  sccm/core/plan-design/changes/whats-new-in-version-1710.md
  sccm/core/plan-design/diagnostics/customer-experience-improvement-program-ceip.md
  sccm/core/plan-design/diagnostics/diagnostics-and-usage-data.md
  sccm/core/plan-design/diagnostics/frequently-asked-questions.md
  sccm/core/plan-design/diagnostics/how-diagnostics-and-usage-data-is-collected.md
  sccm/core/plan-design/diagnostics/how-diagnostics-and-usage-data-is-used.md
  sccm/core/plan-design/diagnostics/levels-of-diagnostic-usage-data-collection-1806.md
  sccm/core/plan-design/diagnostics/levels-of-diagnostic-usage-data-collection-1810.md
  sccm/core/plan-design/diagnostics/levels-of-diagnostic-usage-data-collection-1902.md
  sccm/core/plan-design/diagnostics/levels-of-diagnostic-usage-data-collection-1906.md
  sccm/core/plan-design/diagnostics/levels-of-diagnostic-usage-data-collection-1910.md
  sccm/core/plan-design/diagnostics/levels-overview.md
  sccm/core/plan-design/diagnostics/view-diagnostics-and-usage-data.md
  sccm/core/plan-design/security/additional-privacy.md
  sccm/core/plan-design/security/plan-for-security.md
  sccm/core/servers/deploy/configure/azure-services-wizard.md
  sccm/core/servers/deploy/install/prerequisites-for-installing-sites.md
  sccm/core/servers/manage/management-insights.md
  sccm/core/understand/configuration-manager-and-windows-as-service.md
  sccm/core/understand/frequently-asked-questions-about-diagnostics-and-usage-data.md
  sccm/desktop-analytics/account-close.md
  sccm/desktop-analytics/compat-assessment.md
  sccm/desktop-analytics/enroll-devices.md
  sccm/desktop-analytics/faq.md
  sccm/desktop-analytics/overview.md
  sccm/desktop-analytics/set-up.md
  sccm/sum/deploy-use/optimize-windows-10-update-delivery.md
Labels: do-not-merge
