Repository MicrosoftDocs/SCCMdocs, pull requests merged in 2020-02, with the labels that each got.

#2179 From private repo
  sccm/core/misc/user-experience-analytics-preview.md
  sccm/desktop-analytics/troubleshooting.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2186 From private repo
  sccm/core/TOC.yml
  sccm/core/get-started/2020/includes/2001-2/2356386.md
  sccm/core/get-started/2020/includes/2001-2/3098816.md
  sccm/core/get-started/2020/includes/2001-2/3555777.md
  sccm/core/get-started/2020/includes/2001-2/3555953.md
  sccm/core/get-started/2020/includes/2001-2/3871913.md
  sccm/core/get-started/2020/includes/2001-2/4963230.md
  sccm/core/get-started/2020/includes/2001-2/5686290.md
  sccm/core/get-started/2020/includes/2001-2/5891852.md
  sccm/core/get-started/2020/includes/2001-2/6104290.md
  sccm/core/get-started/2020/includes/2001-2/known-issue-6197183.md
  sccm/core/get-started/2020/includes/2001/2356386.md
  sccm/core/get-started/2020/includes/feature-include-template.md
  sccm/core/get-started/2020/includes/known-issue-include-template.md
  sccm/core/get-started/2020/media/3098816-start-orchestration.png
  sccm/core/get-started/2020/media/3871913-updated-edge-dashboard.png
  sccm/core/get-started/2020/media/5891852-send-smile-status-message.png
  sccm/core/get-started/2020/technical-preview-2001-2.md
  sccm/core/get-started/2020/technical-preview-2001.md
  sccm/core/get-started/capabilities-in-technical-preview-1702.md
  sccm/core/get-started/capabilities-in-technical-preview-1706.md
  sccm/core/get-started/capabilities-in-technical-preview-1805.md
  sccm/core/get-started/technical-preview.md
  sccm/core/misc/cm07-eos.md
  sccm/core/misc/user-experience-analytics-preview.md
  sccm/core/plan-design/changes/whats-new-in-version-1610.md
  sccm/core/plan-design/configs/size-and-scale-numbers.md
  sccm/core/servers/deploy/configure/configure-aoag.md
  sccm/core/servers/manage/cmpivot.md
  sccm/core/servers/manage/replication/overview.md
  sccm/desktop-analytics/faq.md
  sccm/desktop-analytics/overview.md
  sccm/mdm/get-started/install-site-system-roles-for-on-premises-mdm.md
  sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md
  sccm/osd/understand/task-sequence-steps.md
Labels: Change sent to author, configmgr-osd/tech, configuration-manager/prod, do-not-merge

#2187 From private repo
  sccm/core/servers/manage/replication/overview.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2189 From private repo
  sccm/core/TOC.yml
  sccm/core/clients/deploy/about-client-settings.md
  sccm/core/clients/manage/monitor-windows-analytics.md
  sccm/core/clients/manage/upgrade-readiness.md
  sccm/core/get-started/2020/includes/2001-2/4963230.md
  sccm/desktop-analytics/index.yml
  sccm/desktop-analytics/overview.md
  sccm/desktop-analytics/set-up.md
  sccm/desktop-analytics/whats-new.md
  sccm/develop/TOC.yml
  sccm/develop/index.yml
  sccm/index.yml
  sccm/mdm/TOC.yml
  sccm/mdm/index.yml
  sccm/osd/index.yml
Labels: do-not-merge

#2193 From private repo
  sccm/core/misc/user-experience-analytics-preview.md
  sccm/core/plan-design/configs/support-for-windows-10.md
  sccm/core/servers/deploy/configure/site-server-high-availability.md
  sccm/desktop-analytics/compat-assessment.md
  sccm/desktop-analytics/health-status-monitoring.md
  sccm/desktop-analytics/media/app-risk-assessment-sources.png
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2197 Update third-party-software-updates.md
  sccm/sum/deploy-use/third-party-software-updates.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, ready-to-merge

#2199 From private repo
  sccm/core/misc/in-console-documentation.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2200 From private repo
  sccm/apps/deploy-use/install-app-for-device.md
  sccm/apps/pcm/how-to-analyze-and-convert.md
  sccm/core/clients/deploy/about-client-settings.md
  sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md
  sccm/core/servers/deploy/configure/boundary-groups.md
  sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md
  sccm/core/understand/product-and-licensing-faq.md
  sccm/desktop-analytics/overview.md
  sccm/develop/core/servers/console/how-to-find-a-configuration-manager-console-node-guid.md
  sccm/develop/core/understand/sqlviews/sample-queries-compliance-settings-configuration-manager.md
  sccm/osd/deploy-use/manage-task-sequences-to-automate-tasks.md
  sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md
  sccm/protect/deploy-use/bitlocker/encrypt-recovery-data.md
Labels: Change sent to author, configmgr-protect/tech, configuration-manager/prod, do-not-merge

#2190 Update manage-user-state.md
  sccm/osd/get-started/manage-user-state.md
Labels: Change sent to author, assessing_(C&L), configmgr-osd/tech, configuration-manager/prod, ready-to-merge

#2202 From private repo
  sccm/core/support/azure-migration-tool.md
  sccm/sum/deploy-use/office-365-dashboard.md
Labels: Change sent to author, configmgr-sum/tech, configuration-manager/prod, do-not-merge

#2201 rights note for Reporting services point account
  sccm/core/plan-design/hierarchy/accounts.md
Labels: Change sent to author, assessing_(C&L), configmgr-other/tech, configuration-manager/prod, ready-to-merge

#2214 From private repo
  sccm/apps/deploy-use/learn-script-security.md
  sccm/apps/get-started/deploying-app-v-virtual-applications.md
  sccm/core/TOC.yml
  sccm/core/clients/deploy/prerequisites-for-deploying-clients-to-windows-computers.md
  sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard.md
  sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md
  sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md
  sccm/core/get-started/2019/technical-preview-1910.md
  sccm/core/get-started/2020/includes/2002/3098816.md
  sccm/core/get-started/2020/includes/2002/4065163.md
  sccm/core/get-started/2020/includes/2002/4561024.md
  sccm/core/get-started/2020/includes/2002/4639943.md
  sccm/core/get-started/2020/includes/2002/5568051.md
  sccm/core/get-started/2020/includes/2002/5686290.md
  sccm/core/get-started/2020/includes/2002/5913817.md
  sccm/core/get-started/2020/includes/2002/5925683.md
  sccm/core/get-started/2020/includes/2002/5932692.md
  sccm/core/get-started/2020/includes/2002/known-issue-6215446.md
  sccm/core/get-started/2020/media/3098816-reset-og-member.png
  sccm/core/get-started/2020/media/4065163-o365-updates-product-classification.png
  sccm/core/get-started/2020/media/4561024-autoupdate-edge.png
  sccm/core/get-started/2020/technical-preview-2002.md
  sccm/core/get-started/set-up-your-lab.md
  sccm/core/get-started/technical-preview.md
  sccm/core/migration/planning-a-migration-job-strategy.md
  sccm/core/misc/in-console-documentation.md
  sccm/core/misc/user-experience-analytics-preview.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-client.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-server.md
  sccm/core/plan-design/configs/site-and-site-system-prerequisites.md
  sccm/core/plan-design/configs/support-for-virtualization-environments.md
  sccm/core/plan-design/configs/support-for-windows-10.md
  sccm/core/plan-design/configs/support-for-windows-features-and-networks.md
  sccm/core/plan-design/configs/supported-operating-systems-consoles.md
  sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md
  sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md
  sccm/core/plan-design/hierarchy/accounts.md
  sccm/core/plan-design/security/enable-tls-1-2-troubleshoot.md
  sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md
  sccm/core/servers/manage/admin-console.md
  sccm/core/servers/manage/create-queries.md
  sccm/core/servers/manage/media/4640570-search-too-many-results.png
  sccm/core/servers/manage/media/4923997-message-administrator.png
  sccm/core/understand/supported-configurations-for-ltsb.md
  sccm/desktop-analytics/overview.md
  sccm/protect/deploy-use/create-windows-firewall-policies.md
  sccm/protect/plan-design/bitlocker-management.md
  sccm/sum/get-started/configure-classifications-and-products.md
  sccm/sum/get-started/synchronize-software-updates-disconnected.md
  sccm/sum/plan-design/prerequisites-for-software-updates.md
Labels: do-not-merge

#2216 From private repo
  sccm/core/clients/deploy/about-client-installation-properties.md
  sccm/core/plan-design/changes/whats-new-in-version-1910.md
  sccm/core/plan-design/choose-a-device-management-solution.md
  sccm/core/support/tools.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, do-not-merge

#2229 From private repo
  .openpublishing.redirection.json
  sccm/comanage/includes/enable-co-management-1906-and-higher.md
  sccm/comanage/tutorial-co-manage-clients.md
  sccm/comanage/tutorial-co-manage-new-devices.md
  sccm/compliance/TOC.yml
  sccm/compliance/plan-design/scap/about-scap.md
  sccm/compliance/plan-design/scap/deploy-monitor-export.md
  sccm/compliance/plan-design/scap/install-configure-scap.md
  sccm/compliance/plan-design/scap/media/complete-import.png
  sccm/compliance/plan-design/scap/media/complete-report-export.png
  sccm/compliance/plan-design/scap/media/confirm-configuration.png
  sccm/compliance/plan-design/scap/media/confirm-export.png
  sccm/compliance/plan-design/scap/media/deployment-assignment.png
  sccm/compliance/plan-design/scap/media/export-scap-report-datastream.png
  sccm/compliance/plan-design/scap/media/get-to-baselines.png
  sccm/compliance/plan-design/scap/media/import-from-scap-dashboard.png
  sccm/compliance/plan-design/scap/media/import-new-scap-content.png
  sccm/compliance/plan-design/scap/media/import-scap-content.png
  sccm/compliance/plan-design/scap/media/scap-report.png
  sccm/compliance/plan-design/scap/media/select-benchmark-and-profile.png
  sccm/compliance/plan-design/scap/media/select-ci-baseline.png
  sccm/compliance/plan-design/scap/media/select-datastream-file.png
  sccm/compliance/plan-design/scap/media/specify-org-export.png
  sccm/compliance/plan-design/scap/troubleshooting-scap.md
  sccm/core/get-started/capabilities-in-technical-preview-1803.md
  sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md
  sccm/core/plan-design/changes/whats-new-in-version-1806.md
  sccm/core/servers/manage/pre-release-features.md
  sccm/core/support/tools.md
Labels: do-not-merge

#2233 From private repo
  sccm/core/servers/deploy/install/list-of-prerequisite-checks.md
  sccm/core/servers/manage/settings-to-manage-high-risk-deployments.md
  sccm/desktop-analytics/enable-data-sharing.md
  sccm/osd/deploy-use/configure-precache-content.md
  sccm/osd/deploy-use/manage-task-sequences-to-automate-tasks.md
  sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md
Labels: Change sent to author, configmgr-osd/tech, configuration-manager/prod, do-not-merge
